import type { HelpArticle } from './types';

/**
 * Vertex Accounting Help Centre articles. Everything here reflects
 * behaviour that is actually implemented in this build. If a feature is
 * gated by a plan or a permission, the article says so.
 */
export const HELP_ARTICLES: HelpArticle[] = [
  // ─────────────────────────────── Getting started ───────────────────────────────
  {
    id: 'welcome',
    title: 'Welcome to Vertex Accounting',
    category: 'Getting started',
    summary: 'What Vertex is, how the pieces fit together, and where to start.',
    keywords: ['overview', 'introduction', 'start here', 'basics'],
    sections: [
      {
        heading: 'What this is',
        body: 'Vertex is a double-entry accounting system for South African businesses. Every transaction you capture — an invoice, a bill, a bank payment, a stock movement — posts a balanced journal entry to the general ledger. Reports, the trial balance and the VAT return are all built from the ledger, never from the source documents directly.',
      },
      {
        heading: 'The shape of the app',
        body: [
          'Organisation — your company profile, customers and suppliers.',
          'Sales and Purchasing — quotes, orders, invoices, bills, credit notes, payments.',
          'Banking — import statements and reconcile them to the ledger.',
          'Inventory — products, warehouses, stock movements and valuation.',
          'Accounting — chart of accounts, journals, trial balance, financial periods.',
          'Tax & Compliance — VAT, income tax, provisional tax and the compliance dashboard.',
          'Reports — income statement, balance sheet, cash flow, ageing and forecasting.',
          'Administration — users, audit trail, access log, documents, notifications and settings.',
        ],
      },
      {
        heading: 'Where to start',
        body: 'Set up your company first (Company Setup), then your chart of accounts and opening balances, then start capturing transactions. If you were invited to an existing company, most of this is already done — head to the Dashboard.',
      },
    ],
    related: ['company-setup', 'dashboard', 'chart-of-accounts'],
  },
  {
    id: 'company-setup',
    title: 'Setting up your company',
    category: 'Getting started',
    summary: 'Company profile, financial year, VAT registration and the settings the engine relies on.',
    keywords: ['company', 'onboarding', 'financial year', 'year end', 'registration', 'setup'],
    route: '/companies',
    permissions: 'Admin. The first person to create the company becomes its admin automatically.',
    sections: [
      {
        heading: 'What this does',
        body: 'The company record holds the legal entity details plus the accounting configuration the whole system reads: financial year end, accounting basis (accrual or cash), functional and presentation currency, and VAT registration status, filing frequency and basis.',
      },
      {
        heading: 'Before you begin',
        body: 'Have your CIPC registration number, income tax number and — if registered — your VAT number and filing category to hand.',
      },
      {
        heading: 'How to use it',
        body: [
          'Open Company from the sidebar.',
          'Fill in the entity details, then the accounting section: financial year end month and day, accounting basis, currencies.',
          'If you are VAT registered, switch VAT on and set your filing frequency (monthly, every 2 months, etc.) and basis (invoice or payments).',
          'Save. Creating the company also seeds a default South African chart of accounts, a financial year and its 12 periods.',
        ],
      },
      {
        heading: 'Accounting impact',
        body: 'Changing the financial year end after periods exist, or switching the accounting basis after transactions are posted, are high-risk changes. They do not rewrite posted journals, but they change how future periods and reports are built. Every change to these fields is written to the Audit trail with before and after values.',
      },
      {
        heading: 'Common problems',
        body: [
          '"Cannot create a company" — see the troubleshooting article of the same name.',
          'Reporting framework and SBC eligibility can only be changed on this page and always require a recorded reason.',
        ],
      },
    ],
    related: ['accounting-settings', 'chart-of-accounts', 'financial-periods', 'ts-cannot-create-company'],
  },
  {
    id: 'dashboard',
    title: 'The Dashboard',
    category: 'Getting started',
    summary: 'The at-a-glance view of cash, receivables, payables and recent activity.',
    keywords: ['home', 'overview', 'kpi', 'summary'],
    route: '/',
    permissions: 'Any signed-in member of the company.',
    sections: [
      {
        heading: 'What this does',
        body: 'The Dashboard summarises the current financial position from the ledger — bank balances, what customers owe you, what you owe suppliers — plus shortcuts to the things you do most often.',
      },
      {
        heading: 'How to use it',
        body: 'Use the figure cards as a health check. If a number looks wrong, drill into the underlying report (customer ageing, bank accounts, trial balance) rather than assuming the dashboard is stale — every figure is computed live from posted journals.',
      },
    ],
    related: ['welcome', 'reports-centre'],
  },

  // ─────────────────────────────── Sales ───────────────────────────────
  {
    id: 'customers',
    title: 'Customers',
    category: 'Sales',
    summary: 'Keeping the customer list that quotes, invoices and receipts are raised against.',
    keywords: ['debtors', 'clients', 'accounts receivable', 'contacts'],
    route: '/sales/customers',
    permissions: 'Read: everyone. Create/edit: Sales, Accountant, Admin.',
    sections: [
      { heading: 'What this does', body: 'The customer record carries billing details, contact information and payment terms used to default the due date on invoices.' },
      { heading: 'How to use it', body: ['Add a customer before raising their first quote or invoice.', 'Set default payment terms so invoice due dates are calculated for you.', 'Open a customer to see their open balance and document history.'] },
      { heading: 'Accounting impact', body: 'Creating a customer posts nothing. The accounts-receivable control account (1100) only moves when you post an invoice, credit note or receipt.' },
    ],
    related: ['invoices', 'customer-receipts', 'customer-ageing'],
  },
  {
    id: 'quotes-orders',
    title: 'Quotes and sales orders',
    category: 'Sales',
    summary: 'From a quote a customer accepts, to a sales order that commits stock, to an invoice.',
    keywords: ['quote', 'estimate', 'sales order', 'so', 'commitment', 'proforma'],
    route: '/sales/orders',
    permissions: 'Read: everyone. Create/confirm: Sales, Accountant, Admin.',
    sections: [
      { heading: 'What this does', body: 'A quote is a non-binding offer. When it is accepted you convert it to a sales order, which commits inventory (reserves stock without moving it) and tracks how much is still to deliver and to invoice.' },
      { heading: 'How to use it', body: ['Create a quote, send it, then Accept it to create the sales order.', 'From the order, raise a delivery note to ship goods, or invoice directly.', 'The order shows "remaining to deliver" and "remaining to invoice" — both net off returns.'] },
      { heading: 'Accounting impact', body: 'Quotes and sales orders post nothing to the ledger. Only delivery notes (stock) and invoices (revenue, VAT, receivable) post journals.' },
      { heading: 'Common problems', body: 'If a second delivery is rejected as "already delivered", check the order — a return note nets the delivered quantity back down, and both the screen and the database now use the same return-aware formula.' },
    ],
    related: ['delivery-notes', 'invoices', 'inventory-overview'],
  },
  {
    id: 'invoices',
    title: 'Invoices',
    category: 'Sales',
    summary: 'Raising, sending and posting a tax invoice, and what it does to the ledger.',
    keywords: ['tax invoice', 'sales invoice', 'billing', 'revenue'],
    route: '/sales/invoices',
    permissions: 'Read: everyone. Create/edit draft: Sales, Accountant, Admin. Post: Accountant, Admin.',
    accountingImpact: 'Posting an invoice debits Accounts receivable (1100) and credits Sales revenue and the VAT output account. If the line is a stock item, it also debits Cost of sales and credits Inventory (1200) at weighted-average cost.',
    sections: [
      { heading: 'Before you begin', body: 'The customer must exist, the accounting period you are posting into must be open, and stock lines need enough available quantity.' },
      { heading: 'How to use it', body: ['New invoice, pick the customer, add lines (free-text or stock items).', 'Check the tax rate on each line — it defaults from the product or the customer.', 'Save as draft to keep editing, or post it to commit the journal and lock the figures.'] },
      { heading: 'Common problems', body: ['"Invoice won\'t post" — see the troubleshooting article. Usual causes: the period is closed, a stock line exceeds available quantity, or a line has no account/tax rate.', 'A posted invoice is immutable. To correct it, raise a credit note.'] },
    ],
    related: ['credit-notes', 'customer-receipts', 'vat', 'ts-invoice-wont-post', 'financial-periods'],
  },
  {
    id: 'credit-notes',
    title: 'Credit notes',
    category: 'Sales',
    summary: 'Reversing or reducing a posted invoice the correct, auditable way.',
    keywords: ['credit note', 'refund', 'return', 'reverse invoice', 'rebate'],
    route: '/sales/credit-notes',
    permissions: 'Read: everyone. Issue: Sales, Accountant, Admin.',
    accountingImpact: 'A posted credit note reverses the invoice legs proportionally — it credits Accounts receivable and debits Sales revenue and VAT output, and reverses any cost-of-sales/inventory entry for returned stock.',
    sections: [
      { heading: 'What this does', body: 'Posted accounting is never edited. A credit note is the accounting event that undoes part or all of an invoice, with its own number and its own audit trail.' },
      { heading: 'How to use it', body: ['From the invoice, or from Credit Notes, start a new credit note and choose the original invoice.', 'The original-line picker lets you credit specific lines and quantities.', 'Give a reason — it is stored and shown on the document and in the audit trail.'] },
    ],
    related: ['invoices', 'delivery-notes', 'vat'],
  },
  {
    id: 'customer-receipts',
    title: 'Customer receipts and deposits',
    category: 'Sales',
    summary: 'Recording money received from customers and allocating it to invoices.',
    keywords: ['receipt', 'payment received', 'deposit', 'prepayment', 'allocation', '2600'],
    route: '/sales/receipts',
    permissions: 'Read: everyone. Record: Sales, Accountant, Admin.',
    accountingImpact: 'A receipt debits the bank/undeposited-funds account and credits Accounts receivable. An unallocated amount sits in Customer deposits (2600) until you apply it to an invoice.',
    sections: [
      { heading: 'How to use it', body: ['Record a receipt against the customer, enter the amount and the bank account.', 'Allocate it across open invoices, oldest first or by choice.', 'Any surplus becomes a customer deposit and can be applied later.'] },
      { heading: 'Common problems', body: 'If the bank side of a receipt does not appear in reconciliation, check that you recorded it against the correct bank account.' },
    ],
    related: ['invoices', 'bank-reconciliation', 'customer-ageing'],
  },
  {
    id: 'delivery-notes',
    title: 'Delivery notes and return notes',
    category: 'Sales',
    summary: 'Shipping goods against a sales order before invoicing, and handling goods that come back.',
    keywords: ['delivery note', 'dispatch', 'gdn', 'return note', 'grn', 'goods delivered not invoiced'],
    route: '/sales/delivery-notes',
    permissions: 'Read: everyone. Post: Stock controller, Sales, Accountant, Admin.',
    accountingImpact: 'A delivery note moves stock only: it credits Inventory (1200) and debits Goods delivered not invoiced (1220). No revenue, VAT or receivable is touched until the invoice. A return note reverses the same two accounts using the frozen delivery cost.',
    sections: [
      { heading: 'How to use it', body: ['From a confirmed sales order, create a delivery note for the quantity shipped and post it.', 'Invoice the delivered goods later — the invoice picks up the delivery link so nothing is double-counted.', 'If goods come back before invoicing, raise a return note against the delivery note.'] },
      { heading: 'Common problems', body: 'The "remaining to deliver" figure nets off returns. A delivery rejected as over-quantity usually means an earlier delivery has not been returned or the order quantity is lower than you think.' },
    ],
    related: ['quotes-orders', 'invoices', 'inventory-adjustments'],
  },

  // ─────────────────────────────── Purchasing ───────────────────────────────
  {
    id: 'suppliers',
    title: 'Suppliers',
    category: 'Purchasing',
    summary: 'The supplier list that purchase orders, bills and payments are raised against.',
    keywords: ['creditors', 'vendors', 'accounts payable', 'contacts'],
    route: '/purchases/vendors',
    permissions: 'Read: everyone. Create/edit: Accountant, Admin. Stock controller can maintain suppliers used for purchasing.',
    sections: [
      { heading: 'What this does', body: 'Supplier records carry payment terms and banking details used when you capture bills and pay them.' },
      { heading: 'Accounting impact', body: 'None on creation. The accounts-payable control account moves only when you post a bill or a payment.' },
    ],
    related: ['purchase-orders', 'bills', 'supplier-payments', 'supplier-ageing'],
  },
  {
    id: 'purchase-orders',
    title: 'Purchase orders',
    category: 'Purchasing',
    summary: 'Ordering goods or services from a supplier and receiving them into stock.',
    keywords: ['po', 'purchase order', 'goods receipt', 'grni', 'ordering'],
    route: '/purchases/orders',
    permissions: 'Read: everyone. Create: Stock controller, Accountant, Admin. Confirm: Accountant, Admin.',
    accountingImpact: 'Confirming a PO posts nothing. Receiving goods debits Inventory (1200) and credits Goods received not invoiced. Posting the bill clears GRNI against Accounts payable.',
    sections: [
      { heading: 'How to use it', body: ['Create the PO, confirm it, then receive the goods when stock arrives.', 'Create the supplier invoice from the PO when the supplier’s tax invoice comes in.', 'Goods receipt is currently all-or-nothing per PO.'] },
    ],
    related: ['bills', 'suppliers', 'inventory-overview'],
  },
  {
    id: 'bills',
    title: 'Bills and expenses',
    category: 'Purchasing',
    summary: 'Capturing supplier invoices and expenses, with or without a purchase order.',
    keywords: ['bill', 'supplier invoice', 'expense', 'accounts payable', 'input vat'],
    route: '/purchases/bills',
    permissions: 'Read: everyone. Create/edit draft: Stock controller (stock bills), Accountant, Admin. Post: Accountant, Admin.',
    accountingImpact: 'Posting a bill debits the expense or asset account (or clears GRNI) and the VAT input account, and credits Accounts payable.',
    sections: [
      { heading: 'How to use it', body: ['Capture the bill against the supplier, either free-hand or from a purchase order.', 'Split a line across accounts if the expense spans categories.', 'Post it to commit the journal; then pay it from Supplier Payments.'] },
      { heading: 'Common problems', body: '"Journal won\'t post" — check the period is open and every line has an account and a tax rate.' },
    ],
    related: ['purchase-orders', 'supplier-payments', 'vat', 'ts-journal-wont-post'],
  },
  {
    id: 'supplier-payments',
    title: 'Supplier payments',
    category: 'Purchasing',
    summary: 'Paying bills and allocating the payment across them.',
    keywords: ['payment', 'pay supplier', 'remittance', 'accounts payable'],
    route: '/purchases/payments',
    permissions: 'Record: Accountant, Admin.',
    accountingImpact: 'A payment debits Accounts payable and credits the bank account. Allocate it to specific bills so supplier ageing stays correct.',
    sections: [
      { heading: 'How to use it', body: ['Record a payment against the supplier and the bank account, then allocate it to open bills.', 'Reconcile the bank side later against the imported statement.'] },
    ],
    related: ['bills', 'bank-reconciliation', 'supplier-ageing'],
  },

  // ─────────────────────────────── Banking ───────────────────────────────
  {
    id: 'bank-accounts',
    title: 'Bank accounts',
    category: 'Banking',
    summary: 'Setting up a bank account and linking it to a ledger account.',
    keywords: ['bank', 'account', 'cash book', 'gl link'],
    route: '/banking/accounts',
    permissions: 'Create/edit: Accountant, Admin.',
    sections: [
      { heading: 'What this does', body: 'Each bank account is linked to a general-ledger cash account. The ledger account is the source of truth; the bank account screen shows its balance and lets you import statements.' },
      { heading: 'How to use it', body: 'Add the account with its opening balance and the GL account it posts to. From then on, import statements and reconcile.' },
    ],
    related: ['bank-transactions', 'bank-reconciliation'],
  },
  {
    id: 'bank-transactions',
    title: 'Bank transactions and statement import',
    category: 'Banking',
    summary: 'Bringing statement lines in and allocating them to the ledger.',
    keywords: ['statement', 'import', 'csv', 'ofx', 'allocation', 'split'],
    route: '/banking/transactions',
    permissions: 'Import/allocate: Accountant, Admin.',
    accountingImpact: 'Allocating a statement line posts a journal: bank on one side, the account(s) you choose on the other, with VAT split out where applicable.',
    sections: [
      { heading: 'How to use it', body: ['Import the statement file for a bank account.', 'For each line, match it to an existing document (a receipt, a payment) or allocate it to an account, splitting across several accounts and VAT if needed.', 'Matched and allocated lines are then available to reconcile.'] },
    ],
    related: ['bank-reconciliation', 'bank-accounts', 'vat'],
  },
  {
    id: 'bank-reconciliation',
    title: 'Bank reconciliation',
    category: 'Banking',
    summary: 'Agreeing the ledger cash balance to the bank statement, and the review that finds problems.',
    keywords: ['reconcile', 'reconciliation', 'statement balance', 'variance', 'unpresented', 'books integrity'],
    route: '/banking/reconciliation',
    permissions: 'Reconcile: Accountant, Admin.',
    accountingImpact: 'Reconciliation itself posts nothing — it records which transactions are cleared and confirms the ledger agrees with the bank. Any correction you make while reconciling posts its own journal.',
    sections: [
      { heading: 'Before you begin', body: 'Import the statement for the period and allocate or match every line first. Un-allocated lines cannot be reconciled.' },
      { heading: 'How to use it', body: ['Pick the bank account and the statement date.', 'Tick the transactions that appear on the statement. The screen shows the running variance between the adjusted bank balance and the ledger.', 'When the variance is zero, finalise the reconciliation.', 'The reconciliation review (books-integrity investigator) flags likely causes of a non-zero variance — timing offsets, amount mismatches, transpositions, duplicates, missing entries — with the evidence behind each.'] },
      { heading: 'Common problems', body: ['"Bank won\'t reconcile" — the variance is real. Work through the review findings; the most common are a missing ledger entry for a bank charge, a duplicated capture, or a transaction dated in the wrong period.', 'A material set of unresolved reconciliation issues also raises a workspace notification.'] },
    ],
    related: ['bank-transactions', 'notifications', 'ts-bank-wont-reconcile', 'journal-entries'],
  },

  // ─────────────────────────────── Inventory ───────────────────────────────
  {
    id: 'inventory-overview',
    title: 'How inventory accounting works',
    category: 'Inventory',
    summary: 'Weighted-average costing, the 1200 control account, and how stock ties to the ledger.',
    keywords: ['stock', 'inventory', 'wac', 'weighted average', 'valuation', '1200', 'costing'],
    route: '/inventory',
    permissions: 'Read: everyone with the Inventory module. Movements: Stock controller, Accountant, Admin.',
    accountingImpact: 'Every stock movement posts to Inventory (1200). The balance on 1200 in the ledger always equals the physical inventory valuation — that reconciliation is checked on the Inventory Reconciliation report.',
    sections: [
      { heading: 'What this does', body: 'Vertex values stock at weighted-average cost. Each receipt re-averages the unit cost; each issue (sale, transfer out, adjustment down) uses the current average. FIFO is not available for new products in this build.' },
      { heading: 'Before you begin', body: 'Products that carry stock must have "track inventory" on and an inventory, COGS and revenue account (directly or via a category mapping).' },
      { heading: 'Common problems', body: '"Inventory quantity looks wrong" — see the troubleshooting article. Check stock movements for the product and run the Inventory Reconciliation report.' },
    ],
    related: ['inventory-adjustments', 'accounting-settings', 'ts-inventory-quantity-wrong'],
  },
  {
    id: 'inventory-adjustments',
    title: 'Stock adjustments, transfers and stock takes',
    category: 'Inventory',
    summary: 'Correcting on-hand quantities and moving stock between warehouses, the auditable way.',
    keywords: ['adjustment', 'write-off', 'shrinkage', 'transfer', 'stock take', 'stocktake', 'count', 'variance'],
    route: '/inventory/operations',
    permissions: 'Post: Stock controller, Accountant, Admin.',
    accountingImpact: 'An adjustment up debits Inventory (1200) and credits a stock-adjustment/gain account; an adjustment down does the reverse to an expense/loss account. A transfer moves value between warehouse locations without touching the 1200 total. A posted stock take creates the adjusting movements atomically.',
    sections: [
      { heading: 'Before you begin', body: 'Decide the reason and the offset account. The period you are posting into must be open.' },
      { heading: 'How to use it', body: ['Adjustment — pick the product, warehouse, new quantity or delta, reason and account. Post.', 'Transfer — from-warehouse, to-warehouse, quantity. Post.', 'Stock take — enter counted quantities for a warehouse; Vertex computes the variance and posts one atomic set of adjustments when you finalise.'] },
      { heading: 'Common problems', body: ['A negative on-hand balance means an issue was posted before the matching receipt — fix the movement dates, then adjust. Negative balances raise a critical workspace notification.'] },
    ],
    related: ['inventory-overview', 'notifications', 'financial-periods'],
  },

  // ─────────────────────────────── Accounting ───────────────────────────────
  {
    id: 'chart-of-accounts',
    title: 'Chart of accounts',
    category: 'Accounting',
    summary: 'The ledger accounts every transaction posts against, and how to maintain them.',
    keywords: ['coa', 'accounts', 'ledger accounts', 'account codes', 'account types'],
    route: '/accounting/coa',
    permissions: 'Read: everyone. Create/edit: Accountant, Admin.',
    sections: [
      { heading: 'What this does', body: 'A default South African chart is seeded when the company is created. Each account has a code, a type (asset/liability/equity/income/expense) and a normal balance.' },
      { heading: 'How to use it', body: ['Add accounts you need; keep codes consistent with the seeded ranges.', 'An account with posting history can be deactivated but not deleted — its ledger history must stay intact.'] },
      { heading: 'Accounting impact', body: 'Adding or renaming an account posts nothing. Deactivating one stops it appearing in pickers; existing balances are unaffected.' },
    ],
    related: ['general-ledger', 'journal-entries', 'trial-balance'],
  },
  {
    id: 'general-ledger',
    title: 'General ledger and trial balance',
    category: 'Accounting',
    summary: 'The single source of truth — every posted journal line, and the balance of every account.',
    keywords: ['gl', 'ledger', 'trial balance', 'account activity', 'balances'],
    route: '/accounting/ledger',
    permissions: 'Read: everyone. ',
    sections: [
      { heading: 'What this does', body: 'The general ledger is every posted journal line. The trial balance is the sum of debits and credits per account; total debits always equal total credits.' },
      { heading: 'How to use it', body: 'Drill from a report figure to the account, from the account to the journal line, from the line to the source document. Traceability runs in both directions.' },
    ],
    related: ['journal-entries', 'chart-of-accounts', 'trial-balance'],
  },
  {
    id: 'trial-balance',
    title: 'Trial balance',
    category: 'Accounting',
    summary: 'Debits equal credits, always — and how to read the statement.',
    keywords: ['trial balance', 'tb', 'balances', 'debits credits'],
    route: '/accounting/trial-balance',
    sections: [
      { heading: 'How to use it', body: 'Choose the period. Every account with a non-zero balance is listed; the debit and credit totals match. A non-zero difference is not possible with posted journals — if you ever see one, contact support.' },
    ],
    related: ['general-ledger', 'financial-periods'],
  },
  {
    id: 'journal-entries',
    title: 'Journal entries',
    category: 'Accounting',
    summary: 'Manual journals, posting rules, and reversing a journal you got wrong.',
    keywords: ['journal', 'je', 'manual journal', 'adjusting entry', 'reverse', 'accrual', 'provision'],
    route: '/accounting/journals',
    permissions: 'Read: everyone. Post/reverse: Accountant, Admin.',
    accountingImpact: 'A journal posts exactly the debits and credits you enter. Debits must equal credits and the period must be open.',
    sections: [
      { heading: 'Before you begin', body: 'Know the accounts and amounts. Use journals for accruals, provisions, reclassifications and corrections that no source document produces — not for things that should be an invoice, bill or bank allocation.' },
      { heading: 'How to use it', body: ['New journal, enter a memo and the date, add lines until debits equal credits.', 'Post it. A posted journal is immutable.', 'To undo one, use Reverse — it posts an equal-and-opposite journal dated as you choose and links the two. Never try to edit a posted journal.'] },
      { heading: 'Common problems', body: '"Journal won\'t post" — debits do not equal credits, the period is closed, or a line has no account. See the troubleshooting article.' },
    ],
    related: ['financial-periods', 'general-ledger', 'ts-journal-wont-post', 'ts-period-locked'],
  },
  {
    id: 'financial-periods',
    title: 'Financial periods',
    category: 'Accounting',
    summary: 'Open, soft-close, close and lock accounting periods, and why postings get rejected.',
    keywords: ['period', 'close', 'lock', 'reopen', 'month end', 'year end', 'soft close'],
    route: '/financial-periods',
    permissions: 'View: everyone. Manage (open/close/lock/reopen): Accountant, Admin.',
    sections: [
      { heading: 'What this does', body: 'Each financial year has 12 periods. A period is Open, Soft-closed (normal users blocked, managers can still post), Closed (no postings) or Locked. Closing a period stops the figures drifting after you have reported on it.' },
      { heading: 'How to use it', body: ['Finalise the month, then soft-close or close the period.', 'If you must post into a closed period, reopen it — a reason is recorded — post, then close it again.', 'You cannot close the period you would need to reopen to fix your own mistake without the manage permission.'] },
      { heading: 'Common problems', body: ['"Period is locked" — a posting was rejected because its date falls in a closed or locked period. See the troubleshooting article.', 'A period left open more than ~45 days after its end date raises a workspace notification.'] },
    ],
    related: ['journal-entries', 'notifications', 'ts-period-locked'],
  },

  // ─────────────────────────────── Tax & compliance ───────────────────────────────
  {
    id: 'vat',
    title: 'VAT',
    category: 'Tax & compliance',
    summary: 'How the VAT return is built, the difference between output and input VAT, and reconciling it.',
    keywords: ['vat', 'vat201', 'output vat', 'input vat', 'sars', 'tax return', 'vat basis'],
    route: '/tax/vat-return',
    permissions: 'Read: everyone with the VAT module. Prepare/finalise: Accountant, Admin.',
    accountingImpact: 'The VAT return is computed from posted documents in the period — it does not itself post. Finalising records the figures; the payment or refund is a separate bank or journal entry.',
    sections: [
      { heading: 'Before you begin', body: 'Your company must be VAT registered with a filing frequency set (Company page). Every invoice, bill and bank allocation in the period must have the correct tax rate.' },
      { heading: 'How to use it', body: ['Open VAT for the period. Output VAT comes from sales, input VAT from purchases and expenses.', 'Review the transaction lists behind each box — anything with the wrong rate shows up here.', 'Finalise when it agrees.'] },
      { heading: 'Common problems', body: ['"VAT figures differ" from your own spreadsheet — almost always a line captured with the wrong tax rate, a document dated outside the period, or the invoice-vs-payments basis. See the troubleshooting article.', 'A VAT deadline approaching or passed raises a workspace notification for VAT-registered companies.'] },
    ],
    related: ['bills', 'invoices', 'accounting-settings', 'ts-vat-differs', 'notifications'],
  },
  {
    id: 'income-provisional-tax',
    title: 'Income tax and provisional tax',
    category: 'Tax & compliance',
    summary: 'The company income-tax computation, provisional periods, and posting the liability.',
    keywords: ['income tax', 'provisional tax', 'irp6', 'itr14', 'taxable income', 'sbc', 'corporate tax'],
    route: '/tax/income-tax',
    permissions: 'Read: everyone with the module. Post: Accountant, Admin.',
    accountingImpact: 'Posting the income-tax computation debits the tax expense and credits the tax-payable liability. Accounting profit is not taxable income — the computation applies the adjustments you enter.',
    sections: [
      { heading: 'How to use it', body: ['Open the computation for the financial year. It starts from accounting profit and applies your permanent and temporary adjustments.', 'SBC eligibility, if set on the Company page, changes the rate table used.', 'Provisional Tax tracks the first, second and top-up periods for the year.'] },
      { heading: 'Note', body: 'Vertex does not model a shareholder register, so SBC eligibility and dividend allocation are manual, reasoned settings — not auto-determined.' },
    ],
    related: ['company-setup', 'deferred-tax', 'reports-centre'],
  },
  {
    id: 'deferred-tax',
    title: 'Deferred tax and expected credit losses',
    category: 'Tax & compliance',
    summary: 'Temporary differences and the IFRS 9 impairment provision on receivables.',
    keywords: ['deferred tax', 'temporary differences', 'ecl', 'expected credit loss', 'impairment', 'ifrs 9', 'provision'],
    route: '/tax/deferred-tax',
    permissions: 'Read: everyone with the module. Post: Accountant, Admin.',
    sections: [
      { heading: 'What this does', body: 'Deferred tax is computed from the temporary differences between the carrying amount and the tax base of assets — mainly the fixed-asset register versus the wear-and-tear register. Expected credit losses estimate the impairment provision on trade receivables.' },
      { heading: 'How to use it', body: 'Run the computation, review the workings, and post the movement. There is currently no reversal/correction path for a posted tax computation other than a manual journal.' },
    ],
    related: ['fixed-assets', 'customer-ageing', 'journal-entries'],
  },
  {
    id: 'compliance',
    title: 'Compliance dashboard and reporting standards',
    category: 'Tax & compliance',
    summary: 'Public interest score, the audit/review determination, and related-party disclosure.',
    keywords: ['compliance', 'public interest score', 'pis', 'audit', 'independent review', 'reporting framework', 'related parties', 'ifrs'],
    route: '/compliance/dashboard',
    permissions: 'Read: everyone with the module. Maintain register: Accountant, Admin.',
    sections: [
      { heading: 'What this does', body: 'Vertex calculates the public interest score from the data it holds and suggests whether an audit or an independent review is indicated, and which reporting framework fits. It only suggests — a determination is applied by an authorised user with a recorded reason on the Company page.' },
      { heading: 'Related parties', body: 'The related-party register is a manual list. Vertex does not auto-detect relationships or force links from invoices and bills.' },
    ],
    related: ['company-setup', 'income-provisional-tax'],
  },

  // ─────────────────────────────── Fixed assets & payroll ───────────────────────────────
  {
    id: 'fixed-assets',
    title: 'Fixed assets',
    category: 'Fixed assets',
    summary: 'The asset lifecycle: draft, capitalise, depreciate, dispose — and the tax register.',
    keywords: ['fixed asset', 'ppe', 'depreciation', 'disposal', 'capitalise', 'wear and tear', 'sars allowance'],
    route: '/assets/register',
    permissions: 'Read: everyone with the module. Capitalise/depreciate/dispose: Accountant, Admin.',
    accountingImpact: 'Capitalising debits the asset account and clears the acquisition cost from where it sits (often a bill line). Depreciation debits the depreciation expense and credits accumulated depreciation. Disposal removes cost and accumulated depreciation and books the profit or loss.',
    sections: [
      { heading: 'How to use it', body: ['Create the asset (or capitalise it from a bill line), set the method (straight-line or reducing balance) and useful life.', 'Run depreciation for the period — it posts one journal for all due assets.', 'Dispose when sold or scrapped; enter the proceeds.', 'The Asset Tax Register tracks the SARS wear-and-tear allowance separately from book depreciation.'] },
    ],
    related: ['deferred-tax', 'bills', 'journal-entries'],
  },
  {
    id: 'payroll',
    title: 'Payroll',
    category: 'Payroll',
    summary: 'Employees, payroll runs, and the EMP201 / EMP501 returns.',
    keywords: ['payroll', 'salary', 'wages', 'paye', 'uif', 'sdl', 'emp201', 'emp501', 'employees'],
    route: '/payroll/employees',
    permissions: 'Payroll module + Accountant or Admin. Payroll is an add-on, not in the base plans.',
    accountingImpact: 'A posted payroll run debits salaries/wages expense and the employer contributions, and credits the net-pay-payable and statutory-liability accounts (PAYE, UIF, SDL).',
    sections: [
      { heading: 'How to use it', body: ['Add employees with their pay and tax details.', 'Create a payroll run for the month, review PAYE/UIF/SDL for the configured tax year, and post it.', 'EMP201 summarises the month; EMP501 is the reconciliation.'] },
      { heading: 'Not built', body: 'Payslip and IRP5 generation, a mark-as-paid settlement step, and in-app next-year SARS configuration are not in this build.' },
    ],
    related: ['journal-entries', 'plan-billing'],
  },

  // ─────────────────────────────── Reporting ───────────────────────────────
  {
    id: 'reports-centre',
    title: 'Reports',
    category: 'Reporting',
    summary: 'Income statement, balance sheet, cash flow — all built from the ledger.',
    keywords: ['reports', 'income statement', 'profit and loss', 'balance sheet', 'cash flow', 'management accounts', 'export', 'pdf'],
    route: '/reports',
    permissions: 'Read: everyone. Export: Viewer, Finance manager, Accountant, Admin.',
    sections: [
      { heading: 'What this does', body: 'Every report is computed live from posted journals for the period you choose. Nothing is cached from the source documents.' },
      { heading: 'How to use it', body: 'Pick the period and comparison. Drill into any figure to see the accounts and journal lines behind it. Print or export from the report toolbar.' },
      { heading: 'Not built', body: 'Notes to the financial statements and the statement of changes in equity are not yet available.' },
    ],
    related: ['customer-ageing', 'supplier-ageing', 'forecasting', 'general-ledger'],
  },
  {
    id: 'customer-ageing',
    title: 'Customer ageing',
    category: 'Reporting',
    summary: 'What each customer owes, bucketed by how overdue it is.',
    keywords: ['debtors age analysis', 'ageing', 'aged receivables', 'overdue', 'collections'],
    route: '/reports/customer-aging',
    sections: [
      { heading: 'How to use it', body: 'Use the buckets to prioritise collections. A material amount more than 60 days overdue raises a workspace notification and is a candidate for an expected-credit-loss provision.' },
    ],
    related: ['customer-receipts', 'deferred-tax', 'notifications'],
  },
  {
    id: 'supplier-ageing',
    title: 'Supplier ageing',
    category: 'Reporting',
    summary: 'What you owe each supplier, bucketed by age.',
    keywords: ['creditors age analysis', 'ageing', 'aged payables', 'due'],
    route: '/reports/supplier-aging',
    sections: [{ heading: 'How to use it', body: 'Plan payment runs from the buckets. The total agrees to the accounts-payable control account in the trial balance.' }],
    related: ['supplier-payments', 'bills'],
  },
  {
    id: 'forecasting',
    title: 'Forecasting and budget variance',
    category: 'Reporting',
    summary: 'Budget vs forecast vs actual, with evidence-backed variance causes.',
    keywords: ['forecast', 'budget', 'variance', 'projection', 'plan', 'actual vs budget', '6 month', '12 month'],
    route: '/reports/forecasting',
    permissions: 'Read: everyone. Maintain the plan: Accountant, Admin.',
    sections: [
      { heading: 'What this does', body: 'Enter a budget or forecast per account per month. The report shows budget, forecast and actual side by side with the variance and variance %, over 6- or 12-month views.' },
      { heading: 'How to use it', body: ['Capture the plan lines for the year.', 'Review the variance columns each month; drill from a variance into the accounting evidence behind it.'] },
      { heading: 'Common problems', body: 'A budgeted account running materially off budget for the current month raises a workspace notification once budgets are captured.' },
    ],
    related: ['reports-centre', 'notifications', 'general-ledger'],
  },

  // ─────────────────────────────── Administration ───────────────────────────────
  {
    id: 'users-roles',
    title: 'Users and roles',
    category: 'Administration',
    summary: 'Inviting people, access levels, fine-grained roles, and what each can do.',
    keywords: ['users', 'roles', 'permissions', 'invite', 'access level', 'admin', 'accountant', 'viewer', 'bookkeeper'],
    route: '/admin/users',
    permissions: 'Admin only.',
    sections: [
      { heading: 'What this does', body: 'Every user has a coarse access level (admin, accountant, manager, operator, viewer) that the database enforces, and optionally one or more fine-grained roles (e.g. Sales, Stock controller, Finance manager, Bookkeeper) that control which modules and actions they see.' },
      { heading: 'Before you begin', body: 'Decide the least access each person needs. Admin and superuser bypass the fine-grained roles entirely, so only give admin to people who genuinely administer the workspace.' },
      { heading: 'How to use it', body: [
        'Invite a new user — they get a single-use, time-limited, email-bound link to set a password and join.',
        'Add an existing Vertex user — look up their email and add them to the company.',
        'Set their access level, then assign fine-grained roles.',
        'You cannot demote or suspend your own admin access — this prevents locking the company out.',
      ] },
      { heading: 'Common problems', body: ['"Cannot add a user" / "Invitation expired" / "Cannot access a module" / "Why is a module locked?" — each has its own troubleshooting article.'] },
    ],
    related: ['ts-cannot-add-user', 'ts-invitation-expired', 'ts-cannot-access-module', 'ts-module-locked', 'audit-trail', 'access-log'],
  },
  {
    id: 'audit-trail',
    title: 'Audit trail',
    category: 'Administration',
    summary: 'The append-only history of important changes and accounting actions.',
    keywords: ['audit', 'audit trail', 'history', 'who changed what', 'evidence', 'before after'],
    route: '/admin/audit-trail',
    permissions: 'Read: Accountant, Finance manager, Admin.',
    sections: [
      { heading: 'What this does', body: 'The audit trail records semantic business events — "Invoice posted", "Journal reversed", "Stock adjustment posted", "User role changed", "Accounting setting changed" — with the actor, the time, and before/after values. It is append-only: rows cannot be edited or deleted, enforced at the database.' },
      { heading: 'How to use it', body: 'Filter by module, user or date. Open a row to see the full before/after evidence. Use it for review, not for routine navigation.' },
      { heading: 'What is NOT here', body: 'The audit trail is not an activity feed of every click. Routine reads and ordinary navigation are not logged. Successful entry into sensitive areas is recorded in the Access Log instead.' },
    ],
    related: ['access-log', 'users-roles', 'documents'],
  },
  {
    id: 'access-log',
    title: 'Access log',
    category: 'Administration',
    summary: 'Who attempted to open a protected area, and whether it was allowed or denied.',
    keywords: ['access log', 'security log', 'denied', 'permission denied', 'authorization', 'blocked'],
    route: '/admin/audit',
    permissions: 'Read: Accountant, Manager, Admin.',
    sections: [
      { heading: 'What this does', body: 'The access log records security checkpoints: a blocked attempt to open a route the user lacks permission for (denied), and successful entry into a genuinely sensitive area — Users, Audit trail, Payroll, Tax, Plan & billing (allowed). It is append-only.' },
      { heading: 'Kept small on purpose', body: 'Ordinary harmless navigation is not logged, and repeated events from the same user hitting the same checkpoint collapse to one row per hour (server-side de-duplication). A spike in denied events raises a workspace notification.' },
    ],
    related: ['audit-trail', 'users-roles', 'notifications'],
  },
  {
    id: 'documents',
    title: 'Company documents',
    category: 'Administration',
    summary: 'A secure store for CIPC, SARS, VAT, contracts, licences and insurance records.',
    keywords: ['documents', 'files', 'upload', 'attachments', 'cipc', 'sars letter', 'vat certificate', 'contract', 'expiry'],
    route: '/documents',
    permissions: 'Any member of the company can upload and view. Permanent deletion is superuser-only.',
    sections: [
      { heading: 'What this does', body: 'A secure, private store for administrative company records, visible only to your company. Files are held in private storage — never a public link — and downloads use short-lived, single-use links. This is separate from your accounting documents (invoices, bills) which stay in their own modules.' },
      { heading: 'How to use it', body: [
        'Upload a file (PDF, Word, Excel, CSV, PNG, JPEG — max 25 MB), give it a title, category, and optionally a document date and an expiry date.',
        'Set an expiry date on things that lapse — a VAT certificate, a lease, insurance. Vertex raises a notification 30 days before, and again once expired.',
        'Company users archive documents; they are never hard-deleted by a normal user.',
      ] },
      { heading: 'Security', body: 'File identity (name, size, type, who uploaded it and when) is immutable after upload. Every upload, archive, restore and deletion writes an audit-trail row. Company A can never see or download Company B\'s documents.' },
      { heading: 'Common problems', body: '"Document upload failed" — see the troubleshooting article. Usually the file type or the 25 MB size limit.' },
    ],
    related: ['audit-trail', 'notifications', 'ts-document-upload-failed', 'security-privacy'],
  },
  {
    id: 'notifications',
    title: 'Notifications',
    category: 'Administration',
    summary: 'What the bell shows, why, and how to tune it — it is not an activity feed.',
    keywords: ['notifications', 'alerts', 'bell', 'reminders', 'unread', 'mute', 'attention'],
    route: '/notifications',
    permissions: 'Everyone sees notifications targeted at them. Some are limited to admins or to a module your plan includes.',
    sections: [
      { heading: 'What this does', body: 'Notifications flag conditions that need attention — a deadline, a risk, an exception, a failure, a security event, a material variance. They are NOT a log of routine activity: a normal invoice, receipt, journal or stock movement never creates a notification. Those belong in their modules and in the Audit trail.' },
      { heading: 'How it behaves', body: [
        'A notification opens when the condition appears and stays as one item while it persists — a page refresh never creates a duplicate.',
        'It resolves automatically when the condition clears.',
        'If the same condition returns later, it opens again as a fresh item and counts as unread.',
      ] },
      { heading: 'What raises one', body: [
        'A company document expiring within 30 days or already expired.',
        'A material set of unresolved bank reconciliation issues.',
        'A subscription or workspace problem.',
        'A spike in blocked access attempts.',
        'An accounting period left open long after its end date.',
        'A material amount of receivables more than 60 days overdue.',
        'Negative stock balances, or products at/below reorder level.',
        'A budgeted account running materially off budget this month.',
      ] },
      { heading: 'Tuning it', body: 'Settings → Notifications lets you mute non-critical categories (inventory, budget variance, overdue receivables, document expiry). Security, subscription, reconciliation and tax-deadline notifications cannot be muted, and anything marked critical always shows.' },
      { heading: 'Common problems', body: '"Notification won\'t clear" — see the troubleshooting article. The underlying condition is still true; fix that and it resolves on the next evaluation.' },
    ],
    related: ['ts-notification-wont-clear', 'bank-reconciliation', 'documents', 'settings'],
  },
  {
    id: 'settings',
    title: 'Settings',
    category: 'Administration',
    summary: 'Your profile, password, display preferences and notification preferences.',
    keywords: ['settings', 'profile', 'password', 'theme', 'preferences', 'notification settings'],
    route: '/settings',
    permissions: 'Everyone can manage their own profile, password and preferences.',
    sections: [
      { heading: 'What this does', body: 'Personal settings: your name, your password (Supabase Auth), the display theme (light/dark/system), and which non-critical notification categories you want to see.' },
      { heading: 'What is not here', body: 'There is no email or SMS notification toggle — Vertex has no such delivery channel, so a switch that did nothing would be misleading. Company-wide accounting settings are on the Accounting settings page; user administration is on Users & roles.' },
    ],
    related: ['accounting-settings', 'notifications', 'users-roles'],
  },
  {
    id: 'accounting-settings',
    title: 'Accounting settings',
    category: 'Administration',
    summary: 'The company accounting configuration the engine reads, and the account mappings.',
    keywords: ['accounting settings', 'basis', 'currency', 'financial year', 'vat basis', 'account mappings', 'numbering', 'rounding'],
    route: '/settings/accounting',
    permissions: 'View: Accountant, Admin. Edited on the Company page (Admin).',
    sections: [
      { heading: 'What this does', body: 'Shows the accounting settings Vertex actually uses — accounting basis, functional/presentation currency, financial year end, VAT registration, filing frequency and basis — with the live values, and the per-category revenue/COGS/inventory account mappings the posting engine resolves against.' },
      { heading: 'How to change them', body: 'The editable form is on the Company page, so there is one authoritative place. Every change is written to the Audit trail with before and after values, whatever path makes it.' },
      { heading: 'Not configurable', body: 'Document-numbering prefixes, a configurable rounding rule, and a default sales/expense/bank account map are not settings — the engine has no backing for them, so they are not shown as if they were. Each document generates its own next number and amounts round to two decimals.' },
    ],
    related: ['company-setup', 'chart-of-accounts', 'vat', 'audit-trail'],
  },
  {
    id: 'plan-billing',
    title: 'Plan and billing',
    category: 'Administration',
    summary: 'Your Vertex subscription, what it unlocks, and what happens if you downgrade.',
    keywords: ['plan', 'billing', 'subscription', 'upgrade', 'downgrade', 'modules', 'paystack', 'entitlement'],
    route: '/settings/subscription',
    permissions: 'View: Admin. (Superuser can set a plan manually.)',
    sections: [
      { heading: 'What this does', body: 'Shows your current plan and status, the billing interval and current period where real, the management state, and an explicit list of which modules are in your plan and which are on a higher plan.' },
      { heading: 'Downgrade safety', body: 'Changing plan never deletes accounting data. A module you lose becomes read-only — all history, journals and audit records stay intact.' },
      { heading: 'What is not shown', body: 'Payment history, card details, next-debit dates and provider transactions are not shown because online payments are not connected yet. Online checkout is coming; until then, contact Vertex to set up billing.' },
    ],
    related: ['users-roles', 'ts-module-locked', 'ts-company-suspended'],
  },

  // ─────────────────────────────── Security & privacy ───────────────────────────────
  {
    id: 'security-privacy',
    title: 'Security and privacy',
    category: 'Security & privacy',
    summary: 'How your data is isolated, what is logged, and what Vertex support can and cannot see.',
    keywords: ['security', 'privacy', 'popia', 'data protection', 'isolation', 'rls', 'encryption', 'support access'],
    sections: [
      { heading: 'Company isolation', body: 'Every table is scoped to your company at the database with row-level security. A user in one company cannot read, write or download another company\'s data — documents, audit trail, access log, notifications, settings or users — regardless of the URL they try.' },
      { heading: 'What is logged', body: 'Important business changes go to the append-only Audit trail. Security checkpoints (blocked access, entry into sensitive areas) go to the append-only Access log. Neither can be edited or deleted. Sensitive fields — passwords, tokens, invitation secrets, bank and payment details — are never written into audit evidence.' },
      { heading: 'Platform administration', body: 'A Vertex superuser can see workspace configuration health (counts and status), suspend or reactivate a workspace, and adjust a subscription — always audited. They do not see your accounting data: ledger, invoices, balances, payroll or tax figures.' },
      { heading: 'Passwords and sessions', body: 'Authentication is handled by Supabase Auth. Change your password in Settings. If you think an account is compromised, an admin can suspend it on the Users page.' },
    ],
    related: ['audit-trail', 'access-log', 'documents', 'users-roles'],
  },

  // ─────────────────────────────── Troubleshooting ───────────────────────────────
  {
    id: 'ts-cannot-create-company',
    title: "Troubleshooting: I can't create a company",
    category: 'Troubleshooting',
    summary: 'The new-company form fails or nothing happens.',
    keywords: ['cannot create company', 'company creation failed', 'onboarding stuck', 'new company error'],
    sections: [
      { heading: 'What is happening', body: 'Company creation is a single atomic step: it creates the company, makes you its admin, and seeds a chart of accounts, a financial year and 12 periods. If any part fails, the whole thing rolls back so you are never left with a half-made company.' },
      { heading: 'Fix', body: [
        'You can only create a company if you are not already a member of one. If you already belong to a company, you cannot create a second — Vertex is one company per login.',
        'Check every required field is filled: name, entity type, financial year end, currencies.',
        'If it still fails, sign out and back in to refresh your session, then retry. If it persists, contact support with the time it happened — the attempt is in the logs.',
      ] },
    ],
    related: ['company-setup', 'users-roles'],
  },
  {
    id: 'ts-cannot-add-user',
    title: "Troubleshooting: I can't add a user",
    category: 'Troubleshooting',
    summary: 'Adding an existing user does nothing, or the invite is not received.',
    keywords: ['cannot add user', 'add user not working', 'user not appearing', 'invite not received'],
    sections: [
      { heading: 'Adding an existing Vertex user', body: [
        'Use the exact email they signed up with, then Look up, then Add to company.',
        '"No unassigned signup" means that email is not a pending signup — either it does not exist, or it already belongs to a company. Send them an invitation instead.',
        'After adding, refresh — they should still be listed. (An earlier build silently did nothing here; that is fixed.)',
      ] },
      { heading: 'Inviting a new person', body: 'The invite is a single-use, time-limited, email-bound link. If they did not get the email, check spam, then revoke and re-send. Only an admin can add or invite users.' },
    ],
    related: ['users-roles', 'ts-invitation-expired'],
  },
  {
    id: 'ts-invitation-expired',
    title: 'Troubleshooting: my invitation link expired',
    category: 'Troubleshooting',
    summary: 'The accept-invite page says the link is invalid or expired.',
    keywords: ['invitation expired', 'invite link invalid', 'accept invite failed', 'token expired'],
    sections: [
      { heading: 'Why', body: 'Invitation links are single-use and time-limited by design. The link stops working once it is used, once it expires, or if an admin revokes it. The link is also bound to the exact email it was sent to.' },
      { heading: 'Fix', body: 'Ask your admin to send a fresh invitation. Open it in the same browser, signed out, and use the email address it was sent to.' },
    ],
    related: ['users-roles', 'ts-cannot-add-user'],
  },
  {
    id: 'ts-cannot-access-module',
    title: "Troubleshooting: I can't access a module or page",
    category: 'Troubleshooting',
    summary: 'A page shows "Access denied" or is missing from the sidebar.',
    keywords: ['access denied', 'cannot access', 'page missing', 'permission denied', 'no access'],
    sections: [
      { heading: 'Two different reasons', body: [
        'Permission — your fine-grained role does not grant that feature. An admin fixes this on Users & roles by adjusting your access level or roles. Direct-URL navigation to a page you lack permission for shows "Access denied" and is recorded in the Access log.',
        'Plan — the module is not in your company\'s subscription plan. That is a billing question, not a permission one: see "Why is a module locked?".',
      ] },
      { heading: 'Fix', body: 'Ask an admin which of the two it is. If it is permission, they adjust your roles. If it is the plan, an admin looks at Plan & billing.' },
    ],
    related: ['users-roles', 'ts-module-locked', 'access-log'],
  },
  {
    id: 'ts-module-locked',
    title: 'Troubleshooting: why is a module locked?',
    category: 'Troubleshooting',
    summary: 'A module shows a lock icon or an "upgrade" message.',
    keywords: ['module locked', 'upgrade required', 'not in plan', 'feature locked', 'entitlement'],
    sections: [
      { heading: 'Why', body: 'Your company is on a Vertex plan that does not include that module. This is separate from permissions — even an admin sees the lock, because it is a commercial limit, not an access-control one.' },
      { heading: 'Fix', body: [
        'Plan & billing shows exactly which modules are in your plan and which are on a higher one, with the lowest plan that unlocks each.',
        'Your data in a locked module is not deleted — it becomes read-only. Upgrading restores full access with all history intact.',
        'Online checkout is not live yet; contact Vertex to change plan.',
      ] },
    ],
    related: ['plan-billing', 'ts-cannot-access-module'],
  },
  {
    id: 'ts-company-suspended',
    title: 'Troubleshooting: the workspace is suspended',
    category: 'Troubleshooting',
    summary: 'Everyone sees a "workspace suspended" screen instead of the app.',
    keywords: ['company suspended', 'workspace suspended', 'account suspended', 'locked out', 'no access'],
    sections: [
      { heading: 'Why', body: 'A Vertex platform administrator has suspended the workspace — usually a billing matter. While suspended, every company-scoped query returns nothing, so the app shows the suspension screen rather than an empty shell.' },
      { heading: 'Important', body: 'Nothing is deleted. Your ledger, documents and history are all intact and return the moment the workspace is reactivated.' },
      { heading: 'Fix', body: 'Contact Vertex support to resolve the reason and have the workspace reactivated.' },
    ],
    related: ['plan-billing', 'notifications'],
  },
  {
    id: 'ts-invoice-wont-post',
    title: "Troubleshooting: an invoice won't post",
    category: 'Troubleshooting',
    summary: 'The Post button fails or the invoice stays in draft.',
    keywords: ['invoice will not post', 'cannot post invoice', 'invoice error', 'posting failed'],
    sections: [
      { heading: 'Check, in order', body: [
        'The accounting period for the invoice date is Open. A closed or locked period rejects the posting — change the date or reopen the period.',
        'Every line has an account and a tax rate. A blank tax rate on a line blocks the VAT calculation.',
        'Stock lines do not exceed available quantity in the chosen warehouse. Receive or adjust stock first, or reduce the quantity.',
        'The customer still exists and is not archived.',
      ] },
      { heading: 'After posting', body: 'A posted invoice cannot be edited. To change it, raise a credit note against it and issue a corrected invoice.' },
    ],
    related: ['invoices', 'credit-notes', 'financial-periods', 'ts-period-locked'],
  },
  {
    id: 'ts-journal-wont-post',
    title: "Troubleshooting: a journal won't post",
    category: 'Troubleshooting',
    summary: 'The manual journal is rejected on posting.',
    keywords: ['journal will not post', 'cannot post journal', 'unbalanced journal', 'debits credits'],
    sections: [
      { heading: 'Check, in order', body: [
        'Total debits equal total credits, to the cent. The Post button stays disabled until they do.',
        'The period for the journal date is Open.',
        'Every line has an account selected.',
        'You have the "post journals" permission (Accountant or Admin).',
      ] },
      { heading: 'To undo a posted journal', body: 'Use Reverse — never try to edit it. Reverse posts an equal-and-opposite journal and links the two.' },
    ],
    related: ['journal-entries', 'financial-periods', 'ts-period-locked'],
  },
  {
    id: 'ts-bank-wont-reconcile',
    title: "Troubleshooting: the bank won't reconcile",
    category: 'Troubleshooting',
    summary: 'The reconciliation variance will not come down to zero.',
    keywords: ['bank will not reconcile', 'reconciliation variance', 'out of balance', 'statement does not match'],
    sections: [
      { heading: 'The variance is real', body: 'A non-zero variance always means the ledger and the bank genuinely disagree. It is not a display bug.' },
      { heading: 'Work through it', body: [
        'Every statement line for the period must be allocated or matched first — un-allocated lines cannot be ticked.',
        'Open the reconciliation review. It lists likely causes with the evidence: a missing ledger entry (often a bank charge or interest), a duplicated capture, a transaction in the wrong period, a transposed amount, a wrong sign.',
        'Fix each cause at source (post the missing entry, delete the duplicate, correct the date), then return to reconciliation.',
      ] },
      { heading: 'Related', body: 'A material set of unresolved reconciliation issues also shows as a workspace notification until you clear them.' },
    ],
    related: ['bank-reconciliation', 'journal-entries', 'notifications'],
  },
  {
    id: 'ts-inventory-quantity-wrong',
    title: 'Troubleshooting: inventory quantity looks wrong',
    category: 'Troubleshooting',
    summary: 'On-hand stock does not match reality, or a balance is negative.',
    keywords: ['stock quantity wrong', 'negative stock', 'inventory mismatch', 'on hand incorrect'],
    sections: [
      { heading: 'Diagnose', body: [
        'Open the product and review its stock movements — every receipt, sale, transfer and adjustment in date order.',
        'A negative on-hand balance means an issue (sale, transfer out, adjustment down) was posted with a date before the matching receipt. Fix the movement dates.',
        'Run the Inventory Reconciliation report to confirm the ledger Inventory account (1200) agrees with the physical valuation.',
      ] },
      { heading: 'Correct it', body: 'Post a stock adjustment for the difference with a reason and an offset account, or finalise a stock take for the warehouse. Never edit a posted movement.' },
    ],
    related: ['inventory-overview', 'inventory-adjustments', 'notifications'],
  },
  {
    id: 'ts-vat-differs',
    title: 'Troubleshooting: VAT figures differ from what I expected',
    category: 'Troubleshooting',
    summary: 'The VAT return does not match your own calculation.',
    keywords: ['vat wrong', 'vat does not match', 'vat201 difference', 'output input vat mismatch'],
    sections: [
      { heading: 'Usual causes', body: [
        'A line captured with the wrong tax rate — zero-rated vs standard vs exempt. Review the transaction lists behind each box; the offending line is in there.',
        'A document dated just outside the VAT period. Check issue dates at the period boundary.',
        'Invoice basis vs payments basis. On the payments basis, output VAT follows receipts and input VAT follows payments, not the invoice/bill date. Your Company page sets which basis applies.',
        'A credit note or supplier credit not yet posted.',
      ] },
      { heading: 'Fix', body: 'Correct the tax rate or date at source (credit note + re-issue for a posted invoice), then re-open the VAT return.' },
    ],
    related: ['vat', 'invoices', 'bills', 'accounting-settings'],
  },
  {
    id: 'ts-period-locked',
    title: 'Troubleshooting: the period is locked',
    category: 'Troubleshooting',
    summary: 'A posting is rejected because its date falls in a closed or locked period.',
    keywords: ['period locked', 'period closed', 'cannot post to period', 'reopen period'],
    sections: [
      { heading: 'Why', body: 'Closed and locked periods reject postings so that reported figures cannot change after the fact. Soft-closed periods block normal users but still allow managers.' },
      { heading: 'Fix', body: [
        'If the transaction genuinely belongs in an open period, change its date.',
        'If it must go into the closed period, an Accountant or Admin reopens it (a reason is recorded), you post, and they close it again.',
        'Check Financial periods to see the status of each period.',
      ] },
    ],
    related: ['financial-periods', 'journal-entries', 'ts-journal-wont-post'],
  },
  {
    id: 'ts-document-upload-failed',
    title: 'Troubleshooting: a document upload failed',
    category: 'Troubleshooting',
    summary: 'Uploading a company document is rejected.',
    keywords: ['document upload failed', 'file upload error', 'cannot upload', 'file rejected', 'file too large'],
    sections: [
      { heading: 'Check', body: [
        'File type — allowed: PDF, Word (.doc/.docx), Excel (.xls/.xlsx), CSV, PNG, JPEG. SVG, HTML and executables are deliberately blocked.',
        'File size — 25 MB maximum. Compress or split a larger file.',
        'You need an active company. A suspended workspace cannot upload.',
        'A title and a category are required.',
      ] },
      { heading: 'If it still fails', body: 'The bytes are uploaded before the record is written; if the record write fails, the orphaned file is cleaned up automatically, so a failed upload never leaves a stray file. Retry once; if it persists, contact support.' },
    ],
    related: ['documents', 'ts-company-suspended'],
  },
  {
    id: 'ts-notification-wont-clear',
    title: "Troubleshooting: a notification won't clear",
    category: 'Troubleshooting',
    summary: 'You marked it read but it keeps coming back, or it will not resolve.',
    keywords: ['notification will not clear', 'notification keeps coming back', 'cannot dismiss notification', 'alert stuck'],
    sections: [
      { heading: 'Read vs resolved', body: 'Marking a notification read only clears the unread dot for you — it does not resolve the underlying condition. Notifications are condition-driven: they resolve automatically, for everyone, when the condition itself clears.' },
      { heading: 'Fix', body: [
        'Read the notification body — it names the exact condition (e.g. "2 products at or below reorder level", "period April 2026 still open").',
        'Resolve that condition: raise the purchase order, close the period, clear the reconciliation issues, renew the expiring document.',
        'The notification resolves on the next evaluation (within a few minutes, or immediately when you next open the Notifications page).',
        'If it is a non-critical category you do not want to see, mute the category in Settings → Notifications.',
      ] },
    ],
    related: ['notifications', 'settings', 'bank-reconciliation'],
  },

  // ---------------------------------------------------------------------
  // Data Import & Migration Centre + Export Centre
  // ---------------------------------------------------------------------
  {
    id: 'data-migration',
    title: 'Data migration overview',
    category: 'Administration',
    summary: 'Bring accounting data into a Vertex company from another system, or from a Vertex export, with mapping, validation and reconciliation before anything is written.',
    keywords: ['import', 'migration', 'data migration', 'onboarding data', 'move data', 'switch systems', 'pastel', 'sage', 'xero', 'syspro'],
    route: '/admin/imports',
    permissions: 'Accountant, Finance manager, Bookkeeper (full), plus Admin and Superuser. No other role can open the Data Migration pages — migration files can contain complete customer, supplier and banking detail.',
    accountingImpact: 'Master-data imports (Chart of Accounts, Customers, Suppliers, Products) write records only. Opening Stock creates a reviewable draft batch. No import posts to the General Ledger directly.',
    sections: [
      { heading: 'What it does', body: 'Every file goes through the same pipeline: upload → parse → map columns → validate → review issues → confirm → import → audit. Nothing is written until you confirm on the review step.' },
      { heading: 'What you can import today', body: ['Chart of Accounts', 'Customers', 'Suppliers', 'Products / inventory items', 'Opening stock quantities and cost (as a draft batch you confirm from the Inventory module)'] },
      { heading: 'Source systems', body: 'Generic CSV/Excel is fully supported. "Pastel / Sage", "Xero" and "Syspro" are labels only — you upload a CSV or Excel file exported from that system and map its columns by hand (or from a saved profile). There is no live connector to any external accounting system.' },
      { heading: 'Where to start', body: 'Open Administration → Data Migration. Download a blank template from the Data Export page, fill it from your old system, then run the matching import.' },
    ],
    related: ['import-preparing-file', 'import-mapping-profiles', 'import-validation', 'import-history', 'data-export', 'import-accounting-unavailable'],
  },
  {
    id: 'import-preparing-file',
    title: 'Preparing your import file',
    category: 'Administration',
    summary: 'How to get a source file into a shape Vertex can read — one header row, one record per row, consistent dates and numbers.',
    keywords: ['import template', 'prepare file', 'import format', 'header row', 'column headings', 'clean data'],
    route: '/admin/exports',
    sections: [
      { heading: 'Start from a template', body: 'The Data Export page has a blank template for each import type. Its header row is exactly what the importer expects; a column marked with " *" is required.' },
      { heading: 'File rules', body: ['One header row, then one record per row.', 'No merged cells, no blank separator rows, no totals row.', 'Dates in a single consistent format across the whole column.', 'Amounts as plain numbers — no currency symbols, no thousands separators in the cell.', 'Maximum file size 10 MB.'] },
      { heading: 'Codes must match', body: 'An AR/AP or opening-stock file references customers, suppliers or products by their code. Import those master records first so the codes exist. Vertex matches on the exact code — it never guesses by name.' },
    ],
    related: ['import-csv', 'import-excel', 'import-mapping-profiles', 'import-no-fuzzy-mapping', 'data-migration'],
  },
  {
    id: 'import-csv',
    title: 'CSV imports',
    category: 'Administration',
    summary: 'Importing a comma-separated file exported from a spreadsheet or another accounting system.',
    keywords: ['csv', 'comma separated', 'text file', 'import csv'],
    route: '/admin/imports',
    sections: [
      { heading: 'How it works', body: 'A CSV is treated as one worksheet. Vertex reads the first row as headers and every following row as a record, then takes you to the column-mapping step.' },
      { heading: 'Tips', body: ['Save as "CSV UTF-8" from Excel if names contain accented characters.', 'If a field itself contains a comma, the exporting program should quote it — most do automatically.', 'A value that starts with =, +, - or @ is neutralised on export so a spreadsheet never treats it as a formula.'] },
    ],
    related: ['import-excel', 'import-preparing-file', 'import-validation'],
  },
  {
    id: 'import-excel',
    title: 'Excel imports',
    category: 'Administration',
    summary: 'Importing an .xlsx or .xls workbook, including choosing which worksheet holds the data.',
    keywords: ['excel', 'xlsx', 'xls', 'spreadsheet', 'workbook', 'worksheet'],
    route: '/admin/imports',
    sections: [
      { heading: 'How it works', body: 'If the workbook has more than one sheet, Vertex asks which one to import. It then reads that sheet the same way as a CSV — first row as headers.' },
      { heading: 'Tips', body: ['Delete any pivot tables, charts or extra sheets you do not need — only the sheet you pick is read.', 'Formulas are read as their calculated value.', 'Very large workbooks are validated in the browser; keep files under the 10 MB limit and a few thousand rows for a smooth run.'] },
    ],
    related: ['import-csv', 'import-preparing-file', 'import-validation'],
  },
  {
    id: 'import-mapping-profiles',
    title: 'Import mapping profiles',
    category: 'Administration',
    summary: 'Save the column mapping for a file layout so the next file from the same source maps itself.',
    keywords: ['mapping profile', 'column mapping', 'save mapping', 'reusable mapping', 'field mapping'],
    route: '/admin/imports/mappings',
    permissions: 'Same as Data Migration. Company profiles can be created, duplicated and deactivated; system profiles are read-only.',
    sections: [
      { heading: 'What it does', body: 'A profile remembers which source column feeds which Vertex field (and, for account/tax imports, the resolved account and tax mappings). On the next import of the same type from the same source system, pick the profile and the mapping is pre-filled.' },
      { heading: 'How to create one', body: 'Run an import as normal. On the review step, choose "Save mapping as profile" and give it a name (e.g. "ABC Client — Pastel chart of accounts").' },
      { heading: 'Safety', body: 'A restored profile is always shown for confirmation before the import runs. If a mapped account or tax rate no longer exists, that entry is dropped rather than trusted.' },
    ],
    related: ['data-migration', 'import-preparing-file', 'import-no-fuzzy-mapping'],
  },
  {
    id: 'import-validation',
    title: 'Validating an import',
    category: 'Administration',
    summary: 'What the review step checks, and the difference between an error and a warning.',
    keywords: ['import validation', 'validate import', 'import errors', 'import warnings', 'preview import', 'review import'],
    route: '/admin/imports',
    sections: [
      { heading: 'What is checked', body: ['Required fields are present.', 'Dates, numbers and boolean values parse.', 'Referenced codes (customer, supplier, product, account) exist in this company.', 'No contradictory duplicates within the file.'] },
      { heading: 'Errors vs warnings', body: 'A row with a blocking error is never imported. A warning row still imports — for example a record that already exists, where you choose skip / update / treat-as-error on the review step.' },
      { heading: 'After validation', body: 'Every issue is saved against the batch, so you can resolve it later from the Exceptions page without re-uploading the file. Fixing the source file and re-mapping clears the previous run’s issues.' },
    ],
    related: ['import-exceptions', 'import-history', 'import-no-fuzzy-mapping'],
  },
  {
    id: 'import-exceptions',
    title: 'Resolving import exceptions',
    category: 'Administration',
    summary: 'The single list of every unresolved issue across every import batch, with resolve / ignore.',
    keywords: ['import exceptions', 'import issues', 'unresolved import', 'import problems', 'fix import errors'],
    route: '/admin/imports/exceptions',
    sections: [
      { heading: 'What it shows', body: 'Each issue carries its severity, the batch and file it came from, the row and field, a short message and a resolution hint. Filter by errors, warnings or duplicates.' },
      { heading: 'Resolving', body: ['"Mark resolved" — you have dealt with it (fixed the record, or it no longer applies).', '"Ignore" — a deliberate decision to accept it as-is.', 'Neither action changes accounting. To actually re-import corrected rows, fix the source file and run the import again.'] },
      { heading: 'Download', body: 'Export the filtered list as a CSV exception report to work through offline or share with a colleague.' },
    ],
    related: ['import-validation', 'import-history', 'data-migration'],
  },
  {
    id: 'import-history',
    title: 'Import history and batch detail',
    category: 'Administration',
    summary: 'Every import attempt, its status and counts, and the full detail of any one batch.',
    keywords: ['import history', 'import batch', 'past imports', 'import log', 'import status', 'cancel import'],
    route: '/admin/imports/history',
    sections: [
      { heading: 'The list', body: 'Shows date, file, source system, import type, row count and status for every batch. An in-progress batch (uploaded / mapping / ready) can be cancelled — a cancel is a status change, the file and audit trail are kept.' },
      { heading: 'Batch detail', body: ['Status and the imported / updated / error counts.', 'Reconciliation, where the import created a draft.', 'Attached evidence documents.', 'Every issue recorded for the batch.', 'A 60-second signed link to re-download the original source file.'] },
      { heading: 'Statuses', body: 'uploaded → mapping → (validation failed | ready) → importing → (completed | completed with warnings | failed), plus cancelled.' },
    ],
    related: ['import-exceptions', 'import-evidence-documents', 'import-validation'],
  },
  {
    id: 'import-evidence-documents',
    title: 'Import evidence documents',
    category: 'Administration',
    summary: 'Attaching supporting files — legacy trial balances, control totals, signed checklists — to a migration.',
    keywords: ['evidence', 'supporting documents', 'migration evidence', 'working papers', 'control totals', 'import documents'],
    route: '/admin/imports/documents',
    accountingImpact: 'None. An evidence document upload never creates an accounting entry.',
    sections: [
      { heading: 'What it is for', body: 'A place to keep the paper trail behind a data migration: the source-system trial balance, a bank reconciliation as at the migration date, a signed migration checklist, screen captures.' },
      { heading: 'Rules', body: ['PDF, JPG or PNG only, up to 10 MB.', 'Stored privately, scoped to your company — never a public link.', 'Can be linked to a specific batch, or kept general.'] },
      { heading: 'Not the same as Company Documents', body: 'This store is specifically for migration evidence and its batch links. General company records still live in Administration → Documents.' },
    ],
    related: ['import-history', 'documents', 'import-security-isolation'],
  },
  {
    id: 'data-export',
    title: 'Data export centre',
    category: 'Administration',
    summary: 'Export current Vertex data as CSV or Excel, download blank import templates, or build a Vertex Migration Package.',
    keywords: ['export', 'data export', 'download data', 'csv export', 'excel export', 'migration package', 'backup data'],
    route: '/admin/exports',
    permissions: 'Same as Data Migration. You can only export data you have permission to read.',
    sections: [
      { heading: 'Quick exports', body: 'Chart of Accounts, Customers, Suppliers, Trial Balance, General Ledger, and AR/AP opening positions from current ageing — each as CSV or Excel, with stable column headers.' },
      { heading: 'Templates', body: 'Blank header-only files for each import type — the fastest way to prepare a clean import.' },
      { heading: 'Vertex Migration Package', body: 'One JSON file — a manifest plus typed CSV sections, each with its own integrity hash — for backup or moving master data between Vertex environments. It is human-inspectable, never a raw database dump, and never contains secrets or tokens. Upload one back to validate it and re-import a section.' },
    ],
    related: ['data-migration', 'import-preparing-file', 'reports-centre'],
  },
  {
    id: 'import-duplicate-files',
    title: 'Duplicate source files',
    category: 'Administration',
    summary: 'What the "this file was imported before" warning means and what to do about it.',
    keywords: ['duplicate file', 'already imported', 'same file twice', 'file hash', 'reimport'],
    route: '/admin/imports',
    sections: [
      { heading: 'How it is detected', body: 'Vertex fingerprints the exact content of every uploaded file (a SHA-256 hash). If an earlier batch has the identical content, you get a warning naming how many prior batches match.' },
      { heading: 'It is only a warning', body: 'Re-importing the same file is sometimes correct — for example retrying after a failed or cancelled run. The warning never blocks you; check Import History first if it was not intentional.' },
      { heading: 'Duplicate records', body: 'Separate from duplicate files: when rows in the file match records that already exist, you choose skip / update / treat-as-error on the review step.' },
    ],
    related: ['import-history', 'import-validation', 'data-migration'],
  },
  {
    id: 'import-no-fuzzy-mapping',
    title: 'Why Vertex does not use fuzzy mapping',
    category: 'Administration',
    summary: 'Vertex never guesses which account, customer or supplier a row means. Every mapping is exact and confirmed.',
    keywords: ['fuzzy matching', 'auto match', 'name matching', 'guess mapping', 'why exact codes', 'import matching'],
    sections: [
      { heading: 'The rule', body: 'Column-header suggestions and account/tax-code suggestions are exact matches only (case and punctuation insensitive). Nothing is applied silently — every suggestion is shown for you to confirm.' },
      { heading: 'Why', body: 'A near-match on a customer name or account description is exactly how migrated data ends up posted to the wrong account. In accounting the cost of a wrong guess is far higher than the cost of resolving it by hand once.' },
      { heading: 'What to do with an unmatched row', body: 'It goes to Exceptions. Map it explicitly (or create the missing record), then re-run. A saved mapping profile means you only do this once per file layout.' },
    ],
    related: ['import-mapping-profiles', 'import-exceptions', 'import-validation'],
  },
  {
    id: 'import-accounting-unavailable',
    title: 'Why some accounting imports are unavailable',
    category: 'Administration',
    summary: 'Trial Balance, General Ledger detail and AR/AP opening-balance imports are not available yet, on purpose.',
    keywords: ['trial balance import', 'gl import', 'general ledger import', 'ar opening', 'ap opening', 'opening balances import', 'import unavailable', 'import greyed out'],
    route: '/admin/imports',
    sections: [
      { heading: 'What is affected', body: ['Trial Balance import', 'General Ledger detail import', 'AR opening balances import', 'AP opening balances import'] },
      { heading: 'Why', body: 'Each of these would create a journal, and Vertex requires every imported journal to be a reviewable draft that a person posts deliberately — never an automatic post from an uploaded file. That reviewable-draft capability is not built yet, so these imports are shown as "Not available yet" rather than offered in a half-working state.' },
      { heading: 'What you can do now', body: ['Import the Chart of Accounts, then Customers, Suppliers and Products.', 'Capture opening balances as a normal manual journal from Accounting → Journal entries.', 'Import opening stock through the Opening Stock flow, which already produces a draft batch you confirm.'] },
    ],
    related: ['journal-entries', 'chart-of-accounts', 'data-migration', 'inventory-overview'],
  },
  {
    id: 'import-bank-vs-migration',
    title: 'Bank statement import vs data migration',
    category: 'Administration',
    summary: 'Two different tools — bank statements go through Banking, everything else through Data Migration.',
    keywords: ['bank statement import', 'import bank statement', 'ofx', 'bank feed', 'statement vs migration'],
    route: '/banking/transactions',
    sections: [
      { heading: 'Bank statements', body: 'Import a bank statement from the Banking area. It has its own dedicated workflow that keeps the raw source, opening and closing balance, a balance check and full statement lineage, and feeds reconciliation. Parsing a statement never posts to the General Ledger on its own.' },
      { heading: 'Data migration', body: 'Everything else — chart of accounts, customers, suppliers, products, opening stock — goes through Administration → Data Migration.' },
      { heading: 'Why they are separate', body: 'Bank statement handling is a mature, reconciliation-aware engine. Data migration reuses it rather than rebuilding a second, weaker bank import.' },
    ],
    related: ['bank-transactions', 'bank-reconciliation', 'data-migration'],
  },
  {
    id: 'import-security-isolation',
    title: 'Import security and company isolation',
    category: 'Administration',
    summary: 'Where uploaded import files are stored, who can reach them, and how companies are kept apart.',
    keywords: ['import security', 'company isolation', 'private storage', 'signed url', 'import rls', 'who can see import files', 'import privacy'],
    route: '/admin/imports',
    permissions: 'Only Accountant, Finance manager, Bookkeeper, Admin and Superuser can open the Data Migration pages.',
    sections: [
      { heading: 'Storage', body: 'Original source files and evidence documents live in two private storage areas. There is no public link — downloads are short-lived signed URLs generated on demand, and the raw storage path is never shown.' },
      { heading: 'Company isolation', body: 'Every import batch, mapping profile, issue and evidence document is scoped to your company by database row-level security. A user in one company cannot list, download, validate, import or resolve anything belonging to another.' },
      { heading: 'File checks', body: 'The storage area itself enforces the allowed file types (CSV / Excel for sources, PDF / image for evidence) and the 10 MB size limit, so the rule cannot be bypassed by a client that skips the app.' },
      { heading: 'Audit', body: 'File uploads, evidence changes and completed imports are recorded in the Audit Trail with counts only — never raw row content.' },
    ],
    related: ['import-evidence-documents', 'security-privacy', 'audit-trail', 'users-roles'],
  },
];
