import type { Customer } from '@/types';

function nowISO(): string {
  return new Date().toISOString();
}

/**
 * Seed data for MockCustomerRepository (src/repositories/mock/).
 * A spread of realistic South African businesses across provinces, sizes,
 * statuses, payment terms, and credit positions so the customer list's
 * search/filter/sort/aging UI all have something real to show.
 */
export const seedCustomers: Customer[] = [
  {
    id: 'cust_00000001',
    customerNumber: 'CUST-0001',
    name: 'Acme Trading Co.',
    email: 'accounts@acmetrading.example',
    phone: '+27 21 555 0100',
    billingAddress: {
      line1: '12 Market Street',
      city: 'Cape Town',
      state: 'Western Cape',
      postalCode: '8001',
      country: 'South Africa',
    },
    shippingAddress: {
      line1: '12 Market Street',
      city: 'Cape Town',
      state: 'Western Cape',
      postalCode: '8001',
      country: 'South Africa',
    },
    taxNumber: 'VAT4001234567',
    taxStatus: 'taxable',
    currency: 'ZAR',
    balance: 12500.0,
    status: 'active',
    creditLimit: 25000,
    paymentTerms: 'Net30',
    creditHold: false,
    defaultDiscountPercent: 5,
    contacts: [
      { id: 'cont_0001a', name: 'Sipho Mokoena', role: 'Accounts Payable', email: 'sipho@acmetrading.example', phone: '+27 21 555 0101', isPrimary: true },
    ],
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: 'cust_00000002',
    customerNumber: 'CUST-0002',
    name: 'Northwind Distribution',
    email: 'billing@northwind.example',
    phone: '+27 11 555 0101',
    billingAddress: {
      line1: '48 Industrial Ave',
      city: 'Johannesburg',
      state: 'Gauteng',
      postalCode: '2000',
      country: 'South Africa',
    },
    taxStatus: 'taxable',
    currency: 'ZAR',
    balance: 0,
    status: 'active',
    creditLimit: 50000,
    paymentTerms: 'Net60',
    creditHold: false,
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: 'cust_00000003',
    customerNumber: 'CUST-0003',
    name: 'Karoo Agri Supplies',
    email: 'finance@karooagri.example',
    phone: '+27 49 555 0142',
    billingAddress: {
      line1: '7 Voortrekker Road',
      city: 'Graaff-Reinet',
      state: 'Eastern Cape',
      postalCode: '6280',
      country: 'South Africa',
    },
    taxNumber: 'VAT4009988776',
    taxStatus: 'zero-rated',
    currency: 'ZAR',
    balance: 84200.5,
    status: 'active',
    creditLimit: 60000,
    paymentTerms: 'Net30',
    creditHold: true,
    notes: 'Placed on credit hold 2026-07-30 — balance exceeds credit limit pending payment plan.',
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: 'cust_00000004',
    customerNumber: 'CUST-0004',
    name: 'Table Mountain Coffee Roasters',
    email: 'accounts@tmcoffee.example',
    phone: '+27 21 555 0177',
    billingAddress: {
      line1: '203 Long Street',
      city: 'Cape Town',
      state: 'Western Cape',
      postalCode: '8001',
      country: 'South Africa',
    },
    taxStatus: 'taxable',
    currency: 'ZAR',
    balance: 3150.0,
    status: 'active',
    creditLimit: 15000,
    paymentTerms: 'COD',
    creditHold: false,
    defaultDiscountPercent: 2.5,
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: 'cust_00000005',
    customerNumber: 'CUST-0005',
    name: 'Durban Harbour Logistics',
    email: 'ap@durbanharbourlog.example',
    phone: '+27 31 555 0119',
    billingAddress: {
      line1: '88 Bayhead Road',
      city: 'Durban',
      state: 'KwaZulu-Natal',
      postalCode: '4001',
      country: 'South Africa',
    },
    taxNumber: 'VAT4005544332',
    taxStatus: 'taxable',
    currency: 'ZAR',
    balance: 145800.0,
    status: 'active',
    creditLimit: 150000,
    paymentTerms: 'Net60',
    creditHold: false,
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: 'cust_00000006',
    customerNumber: 'CUST-0006',
    name: 'Highveld Steel & Fabrication',
    email: 'billing@highveldsteel.example',
    phone: '+27 13 555 0133',
    billingAddress: {
      line1: '15 Furnace Street',
      city: 'Witbank',
      state: 'Mpumalanga',
      postalCode: '1035',
      country: 'South Africa',
    },
    taxStatus: 'taxable',
    currency: 'ZAR',
    balance: 0,
    status: 'inactive',
    creditLimit: 40000,
    paymentTerms: 'Net30',
    creditHold: false,
    notes: 'Inactivated 2026-04-01 — business closed, no outstanding balance.',
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: 'cust_00000007',
    customerNumber: 'CUST-0007',
    name: 'Pretoria Office Solutions',
    email: 'accounts@pretoriaoffice.example',
    phone: '+27 12 555 0161',
    billingAddress: {
      line1: '56 Church Street',
      city: 'Pretoria',
      state: 'Gauteng',
      postalCode: '0002',
      country: 'South Africa',
    },
    taxNumber: 'VAT4002233445',
    taxStatus: 'taxable',
    currency: 'ZAR',
    balance: 27650.75,
    status: 'active',
    creditLimit: 30000,
    paymentTerms: 'Net14',
    creditHold: false,
    defaultDiscountPercent: 0,
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: 'cust_00000008',
    customerNumber: 'CUST-0008',
    name: 'Gqeberha Marine Chandlers',
    email: 'finance@gqeberhamarine.example',
    phone: '+27 41 555 0188',
    billingAddress: {
      line1: '9 Harbour Arm',
      city: 'Gqeberha',
      state: 'Eastern Cape',
      postalCode: '6001',
      country: 'South Africa',
    },
    taxStatus: 'taxable',
    currency: 'ZAR',
    balance: 61200.0,
    status: 'active',
    creditLimit: 45000,
    paymentTerms: 'Net30',
    creditHold: true,
    notes: 'Over credit limit — awaiting part-payment before releasing new orders.',
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: 'cust_00000009',
    customerNumber: 'CUST-0009',
    name: 'Stellenbosch Wine Exports',
    email: 'ap@stellenboschwine.example',
    phone: '+27 21 555 0144',
    billingAddress: {
      line1: '4 Dorp Street',
      city: 'Stellenbosch',
      state: 'Western Cape',
      postalCode: '7600',
      country: 'South Africa',
    },
    shippingAddress: {
      line1: 'Warehouse 3, Techno Park',
      city: 'Stellenbosch',
      state: 'Western Cape',
      postalCode: '7600',
      country: 'South Africa',
    },
    taxNumber: 'VAT4007766554',
    taxStatus: 'zero-rated',
    currency: 'ZAR',
    balance: 9800.0,
    status: 'active',
    creditLimit: 20000,
    paymentTerms: 'Net30',
    creditHold: false,
    defaultDiscountPercent: 7.5,
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: 'cust_00000010',
    customerNumber: 'CUST-0010',
    name: 'Bloemfontein Medical Supplies',
    email: 'accounts@bfnmedical.example',
    phone: '+27 51 555 0155',
    billingAddress: {
      line1: '22 Nelson Mandela Drive',
      city: 'Bloemfontein',
      state: 'Free State',
      postalCode: '9301',
      country: 'South Africa',
    },
    taxStatus: 'exempt',
    currency: 'ZAR',
    balance: 0,
    status: 'active',
    creditLimit: 35000,
    paymentTerms: 'Net30',
    creditHold: false,
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: 'cust_00000011',
    customerNumber: 'CUST-0011',
    name: 'East London Auto Parts',
    email: 'billing@elautoparts.example',
    phone: '+27 43 555 0166',
    billingAddress: {
      line1: '31 Oxford Street',
      city: 'East London',
      state: 'Eastern Cape',
      postalCode: '5201',
      country: 'South Africa',
    },
    taxNumber: 'VAT4003321990',
    taxStatus: 'taxable',
    currency: 'ZAR',
    balance: 4300.25,
    status: 'inactive',
    creditLimit: 10000,
    paymentTerms: 'COD',
    creditHold: false,
    notes: 'Inactivated 2026-06-15 — dormant account, small residual balance under review.',
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: 'cust_00000012',
    customerNumber: 'CUST-0012',
    name: 'Polokwane Building Merchants',
    email: 'ap@polokwanebuild.example',
    phone: '+27 15 555 0122',
    billingAddress: {
      line1: '18 Landdros Mare Street',
      city: 'Polokwane',
      state: 'Limpopo',
      postalCode: '0699',
      country: 'South Africa',
    },
    taxStatus: 'taxable',
    currency: 'ZAR',
    balance: 52900.0,
    status: 'active',
    creditLimit: 55000,
    paymentTerms: 'Net60',
    creditHold: false,
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: 'cust_00000013',
    customerNumber: 'CUST-0013',
    name: 'Mbombela Hospitality Group',
    email: 'finance@mbombelahospitality.example',
    phone: '+27 13 555 0199',
    billingAddress: {
      line1: '5 Nel Street',
      city: 'Mbombela',
      state: 'Mpumalanga',
      postalCode: '1200',
      country: 'South Africa',
    },
    taxNumber: 'VAT4008812233',
    taxStatus: 'taxable',
    currency: 'ZAR',
    balance: 18750.0,
    status: 'active',
    creditLimit: 25000,
    paymentTerms: 'Net14',
    creditHold: false,
    defaultDiscountPercent: 3,
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: 'cust_00000014',
    customerNumber: 'CUST-0014',
    name: 'Kimberley Diamond Trading Post',
    email: 'accounts@kimberleydtp.example',
    phone: '+27 53 555 0111',
    billingAddress: {
      line1: '2 Jones Street',
      city: 'Kimberley',
      state: 'Northern Cape',
      postalCode: '8301',
      country: 'South Africa',
    },
    taxStatus: 'taxable',
    currency: 'ZAR',
    balance: 96500.0,
    status: 'active',
    creditLimit: 80000,
    paymentTerms: 'Net30',
    creditHold: true,
    notes: 'Credit hold pending resolution of a disputed invoice.',
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
];
