import type { Product } from '@/types';
import { seedStockMovements } from './stockMovements';
import { STANDARD_RATE_ID, ZERO_RATE_ID } from './taxRates';

function nowISO(): string {
  return new Date().toISOString();
}

/**
 * Sums the seeded ledger (src/mock-data/stockMovements.ts) for one product
 * across every warehouse, so each seed product's `quantityOnHand` is
 * DERIVED from the movement history instead of a hand-typed number —
 * exactly the invariant stockService.recordStockMovement enforces at
 * runtime (docs/DO_NOT_BREAK.md § Inventory & Stock).
 */
function sumQuantityOnHand(productId: string): number {
  return seedStockMovements
    .filter((m) => m.productId === productId)
    .reduce((total, m) => total + m.quantityDelta, 0);
}

/**
 * Real TaxRate ids (Phase 5, tax-bee — src/mock-data/taxRates.ts), referenced
 * by Product.taxRateId. Previously these were bespoke placeholder ids that
 * didn't resolve to any real TaxRate record; now they point at the current
 * standard/zero-rated versions so `taxRateService.getTaxRate()` resolves them.
 */
export const PLACEHOLDER_TAX_RATE_STANDARD = STANDARD_RATE_ID;
export const PLACEHOLDER_TAX_RATE_ZERO = ZERO_RATE_ID;

/** Seed data for MockProductRepository (src/features/inventory/repositories/). */
export const seedProducts: Product[] = [
  {
    id: 'prod_00000001',
    sku: 'OFF-PEN-001',
    name: 'Ballpoint Pen (Box of 50)',
    description: 'Medium-tip blue ballpoint pens, box of 50.',
    type: 'good',
    unitPrice: 89.99,
    costPrice: 45,
    taxRateId: PLACEHOLDER_TAX_RATE_STANDARD,
    trackInventory: true,
    quantityOnHand: sumQuantityOnHand('prod_00000001'),
    reorderLevel: 20,
    status: 'active',
    barcode: '6001234500011',
    uom: 'EA',
    category: 'Office Supplies',
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: 'prod_00000002',
    sku: 'OFF-PAP-A4',
    name: 'A4 Copy Paper (Ream)',
    description: '80gsm white A4 copy paper, 500 sheets.',
    type: 'good',
    unitPrice: 119.99,
    costPrice: 65,
    taxRateId: PLACEHOLDER_TAX_RATE_STANDARD,
    trackInventory: true,
    quantityOnHand: sumQuantityOnHand('prod_00000002'),
    reorderLevel: 30,
    status: 'active',
    barcode: '6001234500028',
    uom: 'EA',
    category: 'Office Supplies',
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: 'prod_00000003',
    sku: 'OFF-STA-001',
    name: 'Stapler Heavy Duty',
    description: 'Full-strip heavy duty stapler, 50-sheet capacity.',
    type: 'good',
    unitPrice: 129.99,
    costPrice: 55,
    taxRateId: PLACEHOLDER_TAX_RATE_STANDARD,
    trackInventory: true,
    quantityOnHand: sumQuantityOnHand('prod_00000003'),
    reorderLevel: 10,
    status: 'active',
    uom: 'EA',
    category: 'Office Supplies',
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: 'prod_00000004',
    sku: 'ELE-USB-032',
    name: '32GB USB Flash Drive',
    description: 'USB 3.0 flash drive, 32GB capacity.',
    type: 'good',
    unitPrice: 179.99,
    costPrice: 85,
    taxRateId: PLACEHOLDER_TAX_RATE_STANDARD,
    trackInventory: true,
    quantityOnHand: sumQuantityOnHand('prod_00000004'),
    reorderLevel: 25,
    status: 'active',
    barcode: '6001234500042',
    uom: 'EA',
    category: 'Electronics',
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: 'prod_00000005',
    sku: 'ELE-MOU-001',
    name: 'Wireless Mouse',
    description: '2.4GHz wireless optical mouse.',
    type: 'good',
    unitPrice: 249.99,
    costPrice: 120,
    taxRateId: PLACEHOLDER_TAX_RATE_STANDARD,
    trackInventory: true,
    quantityOnHand: sumQuantityOnHand('prod_00000005'),
    reorderLevel: 15,
    status: 'active',
    uom: 'EA',
    category: 'Electronics',
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: 'prod_00000006',
    sku: 'ELE-KEY-001',
    name: 'Wireless Keyboard',
    description: 'Compact 2.4GHz wireless keyboard.',
    type: 'good',
    unitPrice: 429.99,
    costPrice: 210,
    taxRateId: PLACEHOLDER_TAX_RATE_STANDARD,
    trackInventory: true,
    quantityOnHand: sumQuantityOnHand('prod_00000006'),
    reorderLevel: 10,
    status: 'active',
    uom: 'EA',
    category: 'Electronics',
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: 'prod_00000007',
    sku: 'ELE-HDD-1TB',
    name: '1TB External Hard Drive',
    description: 'USB 3.0 portable external hard drive, 1TB.',
    type: 'good',
    unitPrice: 1099.99,
    costPrice: 650,
    taxRateId: PLACEHOLDER_TAX_RATE_STANDARD,
    trackInventory: true,
    quantityOnHand: sumQuantityOnHand('prod_00000007'),
    reorderLevel: 8,
    status: 'active',
    uom: 'EA',
    category: 'Electronics',
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: 'prod_00000008',
    sku: 'BEV-COF-001',
    name: 'Instant Coffee 750g',
    description: 'Instant coffee granules, 750g jar.',
    type: 'good',
    unitPrice: 159.99,
    costPrice: 95,
    taxRateId: PLACEHOLDER_TAX_RATE_STANDARD,
    trackInventory: true,
    quantityOnHand: sumQuantityOnHand('prod_00000008'),
    reorderLevel: 20,
    status: 'active',
    uom: 'EA',
    category: 'Beverages',
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: 'prod_00000009',
    sku: 'BEV-TEA-001',
    name: 'Rooibos Tea (100 bags)',
    description: 'Pure rooibos tea bags, box of 100.',
    type: 'good',
    unitPrice: 74.99,
    costPrice: 40,
    taxRateId: PLACEHOLDER_TAX_RATE_ZERO,
    trackInventory: true,
    quantityOnHand: sumQuantityOnHand('prod_00000009'),
    reorderLevel: 20,
    status: 'active',
    uom: 'EA',
    category: 'Beverages',
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: 'prod_00000010',
    sku: 'BEV-WAT-500',
    name: 'Bottled Water 500ml (Case of 24)',
    description: 'Still bottled water, 500ml x 24 case.',
    type: 'good',
    unitPrice: 99.99,
    costPrice: 60,
    taxRateId: PLACEHOLDER_TAX_RATE_ZERO,
    trackInventory: true,
    quantityOnHand: sumQuantityOnHand('prod_00000010'),
    reorderLevel: 30,
    status: 'active',
    uom: 'CS',
    category: 'Beverages',
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: 'prod_00000011',
    sku: 'CLN-SAN-005',
    name: 'Hand Sanitiser 5L',
    description: '70% alcohol hand sanitiser, 5L container.',
    type: 'good',
    unitPrice: 299.99,
    costPrice: 180,
    taxRateId: PLACEHOLDER_TAX_RATE_STANDARD,
    trackInventory: true,
    quantityOnHand: sumQuantityOnHand('prod_00000011'),
    reorderLevel: 10,
    status: 'active',
    uom: 'EA',
    category: 'Cleaning',
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: 'prod_00000012',
    sku: 'CLN-WIP-001',
    name: 'Disinfectant Wipes (Pack of 80)',
    description: 'Multi-surface disinfectant wipes, pack of 80.',
    type: 'good',
    unitPrice: 99.99,
    costPrice: 55,
    taxRateId: PLACEHOLDER_TAX_RATE_STANDARD,
    trackInventory: true,
    quantityOnHand: sumQuantityOnHand('prod_00000012'),
    reorderLevel: 15,
    status: 'active',
    uom: 'EA',
    category: 'Cleaning',
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: 'prod_00000013',
    sku: 'CLN-BAG-060',
    name: 'Bin Liners 60L (Roll of 50)',
    description: 'Heavy-duty black bin liners, roll of 50.',
    type: 'good',
    unitPrice: 129.99,
    costPrice: 70,
    taxRateId: PLACEHOLDER_TAX_RATE_STANDARD,
    trackInventory: true,
    quantityOnHand: sumQuantityOnHand('prod_00000013'),
    reorderLevel: 15,
    status: 'active',
    uom: 'EA',
    category: 'Cleaning',
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: 'prod_00000014',
    sku: 'PKG-BOX-M',
    name: 'Medium Shipping Box',
    description: 'Corrugated shipping box, 350x250x200mm.',
    type: 'good',
    unitPrice: 24.99,
    costPrice: 12,
    taxRateId: PLACEHOLDER_TAX_RATE_STANDARD,
    trackInventory: true,
    quantityOnHand: sumQuantityOnHand('prod_00000014'),
    reorderLevel: 100,
    status: 'active',
    uom: 'EA',
    category: 'Packaging',
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: 'prod_00000015',
    sku: 'PKG-TAP-048',
    name: 'Packing Tape 48mm',
    description: 'Clear packing tape, 48mm x 100m roll.',
    type: 'good',
    unitPrice: 34.99,
    costPrice: 18,
    taxRateId: PLACEHOLDER_TAX_RATE_STANDARD,
    trackInventory: true,
    quantityOnHand: sumQuantityOnHand('prod_00000015'),
    reorderLevel: 40,
    status: 'active',
    uom: 'EA',
    category: 'Packaging',
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: 'prod_00000016',
    sku: 'PKG-BUB-10M',
    name: 'Bubble Wrap 10m Roll',
    description: 'Small-bubble cushioning wrap, 10m roll.',
    type: 'good',
    unitPrice: 119.99,
    costPrice: 65,
    taxRateId: PLACEHOLDER_TAX_RATE_STANDARD,
    trackInventory: true,
    quantityOnHand: sumQuantityOnHand('prod_00000016'),
    reorderLevel: 20,
    status: 'active',
    uom: 'EA',
    category: 'Packaging',
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: 'prod_00000017',
    sku: 'SRV-DEL-STD',
    name: 'Standard Delivery Service',
    description: 'Standard courier delivery, per shipment.',
    type: 'service',
    unitPrice: 149.99,
    costPrice: 0,
    taxRateId: PLACEHOLDER_TAX_RATE_STANDARD,
    trackInventory: false,
    quantityOnHand: 0,
    status: 'active',
    uom: 'EA',
    category: 'Services',
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: 'prod_00000018',
    sku: 'SRV-INS-SET',
    name: 'On-site Installation Service',
    description: 'On-site equipment installation and setup, per visit.',
    type: 'service',
    unitPrice: 899.99,
    costPrice: 0,
    taxRateId: PLACEHOLDER_TAX_RATE_STANDARD,
    trackInventory: false,
    quantityOnHand: 0,
    status: 'inactive',
    uom: 'EA',
    category: 'Services',
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
];
