import type { Supplier } from '@/types';

function nowISO(): string {
  return new Date().toISOString();
}

/**
 * Seed data for MockSupplierRepository
 * (src/features/suppliers/repositories/MockSupplierRepository.ts).
 *
 * ~15 realistic South African vendors spanning every category/status/
 * payment-term/on-hold combination so list search, filter, sort, and
 * aging all have something real to render.
 */
export const seedSuppliers: Supplier[] = [
  {
    id: 'sup_00000001',
    supplierNumber: 'SUP-0001',
    name: 'Highveld Steel & Fabrication (Pty) Ltd',
    email: 'accounts@highveldsteel.example',
    phone: '+27 11 555 0201',
    contactPerson: 'Riaan Botha',
    address: {
      line1: '14 Rand Road',
      city: 'Germiston',
      state: 'Gauteng',
      postalCode: '1401',
      country: 'South Africa',
    },
    taxNumber: 'VAT4780123456',
    currency: 'ZAR',
    balance: 84250.0,
    creditLimit: 150000,
    category: 'Raw Materials',
    paymentTerms: 'Net30',
    paymentMethod: 'EFT',
    settlementDiscountPercent: 2.5,
    status: 'active',
    onHold: false,
    bankDetails: { bankName: 'Standard Bank', branchCode: '051001', accountNumber: '012345678' },
    notes: 'Primary structural steel supplier for the Midrand plant.',
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: 'sup_00000002',
    supplierNumber: 'SUP-0002',
    name: 'Cape Coastal Timber Merchants',
    email: 'orders@capecoastaltimber.example',
    phone: '+27 21 555 0202',
    contactPerson: 'Elzabe Kruger',
    address: {
      line1: '77 Voortrekker Road',
      city: 'Bellville',
      state: 'Western Cape',
      postalCode: '7530',
      country: 'South Africa',
    },
    taxNumber: 'VAT4780123457',
    currency: 'ZAR',
    balance: 12600.5,
    creditLimit: 60000,
    category: 'Raw Materials',
    paymentTerms: 'Net14',
    paymentMethod: 'EFT',
    status: 'active',
    onHold: false,
    bankDetails: { bankName: 'FNB', branchCode: '250655', accountNumber: '62012345601' },
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: 'sup_00000003',
    supplierNumber: 'SUP-0003',
    name: 'Eskom Business Services',
    email: 'billing@eskombusiness.example',
    phone: '+27 86 003 7566',
    contactPerson: 'National Accounts Desk',
    address: {
      line1: 'Megawatt Park, Maxwell Drive',
      city: 'Sandton',
      state: 'Gauteng',
      postalCode: '2196',
      country: 'South Africa',
    },
    taxNumber: 'VAT4190000418',
    currency: 'ZAR',
    balance: 45870.32,
    creditLimit: 0,
    category: 'Utilities',
    paymentTerms: 'Net14',
    paymentMethod: 'Direct Debit',
    status: 'active',
    onHold: false,
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: 'sup_00000004',
    supplierNumber: 'SUP-0004',
    name: 'City of Johannesburg Municipal Services',
    email: 'accounts@joburg.example',
    phone: '+27 11 555 0203',
    address: {
      line1: '158 Civic Boulevard',
      city: 'Johannesburg',
      state: 'Gauteng',
      postalCode: '2001',
      country: 'South Africa',
    },
    currency: 'ZAR',
    balance: 9820.0,
    creditLimit: 0,
    category: 'Utilities',
    paymentTerms: 'Net30',
    paymentMethod: 'Direct Debit',
    status: 'active',
    onHold: false,
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: 'sup_00000005',
    supplierNumber: 'SUP-0005',
    name: 'Sasol Fuel Distributors',
    email: 'accounts@sasoldistributors.example',
    phone: '+27 11 555 0204',
    contactPerson: 'Thabo Nkosi',
    address: {
      line1: '1 Sturdee Avenue',
      city: 'Rosebank',
      state: 'Gauteng',
      postalCode: '2196',
      country: 'South Africa',
    },
    taxNumber: 'VAT4780123458',
    currency: 'ZAR',
    balance: 132400.75,
    creditLimit: 100000,
    category: 'Utilities',
    paymentTerms: 'Net30',
    paymentMethod: 'EFT',
    status: 'active',
    onHold: true,
    bankDetails: { bankName: 'ABSA', branchCode: '632005', accountNumber: '4056789012' },
    notes: 'Placed on hold pending credit limit review — currently over agreed terms.',
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: 'sup_00000006',
    supplierNumber: 'SUP-0006',
    name: 'Durban Office Solutions',
    email: 'sales@durbanoffice.example',
    phone: '+27 31 555 0205',
    contactPerson: 'Priya Naidoo',
    address: {
      line1: '22 Umgeni Business Park',
      city: 'Durban',
      state: 'KwaZulu-Natal',
      postalCode: '4001',
      country: 'South Africa',
    },
    taxNumber: 'VAT4780123459',
    currency: 'ZAR',
    balance: 3450.0,
    creditLimit: 25000,
    category: 'Trade Vendors',
    paymentTerms: 'Net30',
    paymentMethod: 'Credit Card',
    settlementDiscountPercent: 5,
    status: 'active',
    onHold: false,
    bankDetails: { bankName: 'Nedbank', branchCode: '198765', accountNumber: '1122334455' },
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: 'sup_00000007',
    supplierNumber: 'SUP-0007',
    name: 'Vaal Logistics & Freight',
    email: 'invoices@vaallogistics.example',
    phone: '+27 16 555 0206',
    contactPerson: 'Johan van der Merwe',
    address: {
      line1: '9 Freight Way',
      city: 'Vanderbijlpark',
      state: 'Gauteng',
      postalCode: '1911',
      country: 'South Africa',
    },
    taxNumber: 'VAT4780123460',
    currency: 'ZAR',
    balance: 61200.0,
    creditLimit: 80000,
    category: 'Services',
    paymentTerms: 'Net30',
    paymentMethod: 'EFT',
    status: 'active',
    onHold: false,
    bankDetails: { bankName: 'Standard Bank', branchCode: '051001', accountNumber: '098765432' },
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: 'sup_00000008',
    supplierNumber: 'SUP-0008',
    name: 'Karoo Packaging Supplies',
    email: 'accounts@karoopackaging.example',
    phone: '+27 49 555 0207',
    address: {
      line1: '5 Church Street',
      city: 'Graaff-Reinet',
      state: 'Eastern Cape',
      postalCode: '6280',
      country: 'South Africa',
    },
    currency: 'ZAR',
    balance: 0,
    creditLimit: 20000,
    category: 'Raw Materials',
    paymentTerms: 'EOM',
    paymentMethod: 'EFT',
    status: 'inactive',
    onHold: false,
    notes: 'No orders placed in the last 12 months — marked inactive.',
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: 'sup_00000009',
    supplierNumber: 'SUP-0009',
    name: 'Pretoria IT Managed Services',
    email: 'billing@pretoriait.example',
    phone: '+27 12 555 0208',
    contactPerson: 'Sarah van Zyl',
    address: {
      line1: '303 Lynnwood Road',
      city: 'Pretoria',
      state: 'Gauteng',
      postalCode: '0081',
      country: 'South Africa',
    },
    taxNumber: 'VAT4780123461',
    currency: 'ZAR',
    balance: 18750.0,
    creditLimit: 40000,
    category: 'Services',
    paymentTerms: 'Net30',
    paymentMethod: 'Direct Debit',
    settlementDiscountPercent: 1.5,
    status: 'active',
    onHold: false,
    bankDetails: { bankName: 'Capitec Business', branchCode: '470010', accountNumber: '1500223344' },
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: 'sup_00000010',
    supplierNumber: 'SUP-0010',
    name: 'Nelspruit Agri Equipment',
    email: 'sales@nelspruitagri.example',
    phone: '+27 13 555 0209',
    contactPerson: 'Pieter Fourie',
    address: {
      line1: '61 Nel Street',
      city: 'Mbombela',
      state: 'Mpumalanga',
      postalCode: '1200',
      country: 'South Africa',
    },
    taxNumber: 'VAT4780123462',
    currency: 'ZAR',
    balance: 96430.4,
    creditLimit: 70000,
    category: 'Raw Materials',
    paymentTerms: 'Net14',
    paymentMethod: 'EFT',
    status: 'active',
    onHold: true,
    bankDetails: { bankName: 'ABSA', branchCode: '632005', accountNumber: '4090011223' },
    notes: 'Over credit limit — on hold until part-payment is received.',
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: 'sup_00000011',
    supplierNumber: 'SUP-0011',
    name: 'Bloemfontein Cleaning & Hygiene Co.',
    email: 'accounts@bfncleaning.example',
    phone: '+27 51 555 0210',
    address: {
      line1: '18 Nelson Mandela Drive',
      city: 'Bloemfontein',
      state: 'Free State',
      postalCode: '9301',
      country: 'South Africa',
    },
    currency: 'ZAR',
    balance: 2100.0,
    creditLimit: 15000,
    category: 'Services',
    paymentTerms: 'Net30',
    paymentMethod: 'EFT',
    status: 'active',
    onHold: false,
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: 'sup_00000012',
    supplierNumber: 'SUP-0012',
    name: 'Port Elizabeth Marine Chandlers',
    email: 'orders@pemarine.example',
    phone: '+27 41 555 0211',
    contactPerson: 'Wendy Adams',
    address: {
      line1: '4 Harbour Approach',
      city: 'Gqeberha',
      state: 'Eastern Cape',
      postalCode: '6001',
      country: 'South Africa',
    },
    taxNumber: 'VAT4780123463',
    currency: 'ZAR',
    balance: 27650.0,
    creditLimit: 45000,
    category: 'Trade Vendors',
    paymentTerms: 'Net30',
    paymentMethod: 'EFT',
    status: 'active',
    onHold: false,
    bankDetails: { bankName: 'Nedbank', branchCode: '198765', accountNumber: '2233445566' },
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: 'sup_00000013',
    supplierNumber: 'SUP-0013',
    name: 'Polokwane Print & Signage',
    email: 'studio@polokwaneprint.example',
    phone: '+27 15 555 0212',
    address: {
      line1: '11 Landros Mare Street',
      city: 'Polokwane',
      state: 'Limpopo',
      postalCode: '0699',
      country: 'South Africa',
    },
    currency: 'ZAR',
    balance: 0,
    creditLimit: 10000,
    category: 'Services',
    paymentTerms: 'EOM',
    paymentMethod: 'Credit Card',
    status: 'inactive',
    onHold: false,
    notes: 'Contract lapsed; not currently used for print work.',
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: 'sup_00000014',
    supplierNumber: 'SUP-0014',
    name: 'Stellenbosch Electrical Wholesalers',
    email: 'accounts@stellenboschelectrical.example',
    phone: '+27 21 555 0213',
    contactPerson: 'Marisa Loubser',
    address: {
      line1: '30 Bird Street',
      city: 'Stellenbosch',
      state: 'Western Cape',
      postalCode: '7600',
      country: 'South Africa',
    },
    taxNumber: 'VAT4780123464',
    currency: 'ZAR',
    balance: 54300.9,
    creditLimit: 90000,
    category: 'Raw Materials',
    paymentTerms: 'Net30',
    paymentMethod: 'EFT',
    settlementDiscountPercent: 3,
    status: 'active',
    onHold: false,
    bankDetails: { bankName: 'Standard Bank', branchCode: '051001', accountNumber: '076554321' },
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: 'sup_00000015',
    supplierNumber: 'SUP-0015',
    name: 'East London Fleet Maintenance',
    email: 'workshop@elfleet.example',
    phone: '+27 43 555 0214',
    contactPerson: 'Sipho Mkhize',
    address: {
      line1: '87 Devereux Avenue',
      city: 'East London',
      state: 'Eastern Cape',
      postalCode: '5201',
      country: 'South Africa',
    },
    taxNumber: 'VAT4780123465',
    currency: 'ZAR',
    balance: 41250.0,
    creditLimit: 55000,
    category: 'Services',
    paymentTerms: 'Net14',
    paymentMethod: 'EFT',
    status: 'active',
    onHold: false,
    bankDetails: { bankName: 'FNB', branchCode: '250655', accountNumber: '62099887766' },
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
];
