import type { SourceSystem } from './types';

export interface SourceSystemProfile {
  id: SourceSystem;
  label: string;
  description: string;
  /** What Phase D actually supports for this system — always file-based, never a claim of live/API integration unless one genuinely exists. */
  supportedFormats: string[];
  /** Import types this profile is realistically useful for, given only generic CSV/Excel column mapping is available. */
  applicableImportTypes: string[];
  knownLimitations: string[];
}

/**
 * D0/D-mission finding, unchanged by this build: no Pastel/Sage, Xero, or
 * Syspro sample export file or documented column layout exists anywhere in
 * this codebase or repo history. Per the mission's own repeated rule
 * ("Do NOT display 'Upload Pastel backup' unless that exact backup parser
 * exists" / "inspect real known export formats before claiming support"),
 * these profiles are DELIBERATELY informational/labeling only — they set
 * `import_batches.source_system` (for filtering/reporting in Import
 * History) and let a user save a named mapping profile per system, but the
 * actual column matching for every one of them still runs through the
 * SAME generic, exact-alias `suggestColumnMapping()` every adapter already
 * uses. No system-specific column alias is injected here, because none has
 * been verified against a real export from that system. When a real sample
 * file is supplied, the right extension point is each adapter's own
 * `aliases` list (evidence-based, reviewable) — not this registry.
 */
export const SOURCE_SYSTEM_PROFILES: SourceSystemProfile[] = [
  {
    id: 'generic',
    label: 'Generic CSV / Excel',
    description: 'Any CSV, XLS or XLSX export — column mapping is done by hand or from a saved profile.',
    supportedFormats: ['.csv', '.xls', '.xlsx'],
    applicableImportTypes: ['chart_of_accounts', 'trial_balance', 'customers', 'suppliers', 'ar_opening', 'ap_opening', 'products', 'opening_stock'],
    knownLimitations: [],
  },
  {
    id: 'pastel_sage',
    label: 'Pastel / Sage',
    description: 'Upload a CSV or Excel file exported from Pastel/Sage — map its columns on the next step.',
    supportedFormats: ['.csv', '.xls', '.xlsx'],
    applicableImportTypes: ['chart_of_accounts', 'trial_balance', 'customers', 'suppliers', 'ar_opening', 'ap_opening', 'products'],
    knownLimitations: [
      'No native Pastel/Sage database or backup file format is read — only an exported CSV/Excel file.',
      'No verified Pastel/Sage export layout is built into this centre yet; map columns manually on the Mapping step, then save it as a named profile so the next file from the same client maps itself.',
    ],
  },
  {
    id: 'xero',
    label: 'Xero',
    description: 'Upload a CSV or Excel file exported from Xero — map its columns on the next step.',
    supportedFormats: ['.csv', '.xls', '.xlsx'],
    applicableImportTypes: ['chart_of_accounts', 'trial_balance', 'customers', 'suppliers', 'ar_opening', 'ap_opening', 'products'],
    knownLimitations: [
      'This is a file-based import, not a live Xero API/OAuth connection — no such integration exists in this build.',
      'No verified Xero export layout is built into this centre yet; map columns manually on the Mapping step, then save it as a named profile.',
    ],
  },
  {
    id: 'syspro',
    label: 'Syspro',
    description: 'Upload a CSV or Excel file exported from Syspro — map its columns on the next step.',
    supportedFormats: ['.csv', '.xls', '.xlsx'],
    applicableImportTypes: ['chart_of_accounts', 'trial_balance', 'customers', 'suppliers', 'ar_opening', 'ap_opening', 'products'],
    knownLimitations: [
      'Syspro installations vary by version/configuration — no single fixed column layout is assumed. Map columns manually, then save a named profile per client.',
    ],
  },
  {
    id: 'vertex_package',
    label: 'Vertex Migration Package',
    description: 'Re-import a structured export package this Vertex instance previously generated (Export Centre → Migration Package).',
    supportedFormats: ['.json'],
    applicableImportTypes: ['vertex_package'],
    knownLimitations: ['Only a package generated by this same Vertex schema version can be re-imported — see migrationPackage.ts.'],
  },
];

export function getSourceSystemProfile(id: SourceSystem): SourceSystemProfile {
  return SOURCE_SYSTEM_PROFILES.find((p) => p.id === id) ?? SOURCE_SYSTEM_PROFILES[0];
}
