import type { BaseEntity, ID, ISODateString } from './common';

/**
 * Lessee-side lease lifecycle (this application never plays the role of
 * lessor — SA_ACCOUNTING_MASTER_SPEC.md §32, §47/IFRS 16).
 * 'draft': registered but not yet commenced — no journal entry posted yet,
 * excluded from amortization runs, mirrors FixedAssetStatus's 'draft'.
 * 'active': commencement has been posted (DR Right-of-Use Asset / CR Lease
 * Liability); amortizing.
 * 'terminated': terminated via leaseDisposalService.terminateLease();
 * terminal, mirrors FixedAssetStatus's 'disposed'.
 */
export type LeaseStatus = 'draft' | 'active' | 'terminated';

/**
 * A single lessee lease contract (SA_ACCOUNTING_MASTER_SPEC.md §32
 * "LEASES", §47 "IFRS 16"). `initialLeaseLiability`/`initialRightOfUseAsset`
 * are computed once at `createLease()` time from the present value of the
 * fixed monthly payment annuity (see
 * `calculateLeaseLiabilityPresentValue()`, src/features/leases/services/leaseCalculations.ts)
 * and never change afterwards — they are the lease's original cost basis,
 * same role as FixedAsset.cost. `accumulatedDepreciation`/
 * `outstandingLeaseLiability` are running totals maintained ONLY by
 * leaseAmortizationService.runAmortization(), the same "stored running
 * total, written only through its owning service" pattern as
 * FixedAsset.accumulatedDepreciation — never set directly by a form.
 *
 * Deliberately simplified vs. full IFRS 16 (documented scope boundaries,
 * not oversights — see docs/SA_SPEC_GAP_ANALYSIS.md):
 *  - No escalation clauses: `monthlyPayment` is a single fixed figure for
 *    the whole term.
 *  - No lease incentives or initial direct costs:
 *    `initialRightOfUseAsset` always equals `initialLeaseLiability` exactly.
 *  - No modifications/remeasurement: a change in terms requires
 *    terminating and re-creating the lease, there is no in-place
 *    remeasurement of the liability/ROU asset.
 *  - No sublease accounting.
 *  - `discountRatePercent` (the incremental borrowing rate) is ALWAYS a
 *    manual input — there is no market-rate lookup in this codebase, same
 *    "don't guess" principle as Deferred Tax's loss-recognition rates.
 */
export interface LeaseContract extends BaseEntity {
  /** Optional, mirrors FixedAsset's lack of a companyId — this app is single-tenant. */
  companyId?: ID;
  /** e.g. "LSE-0001" — auto-generated by leaseService.createLease(), same sequential numbering convention as FixedAsset.assetNumber. */
  leaseNumber: string;
  lessorName: string;
  assetDescription: string;
  commencementDate: ISODateString;
  leaseTermMonths: number;
  /** Fixed monthly payment — no escalation clauses modeled, see the type-level doc comment. */
  monthlyPayment: number;
  /** Annual incremental borrowing rate, e.g. 10 for 10%. Always a manual input. */
  discountRatePercent: number;
  status: LeaseStatus;
  /** PV of the payment annuity at commencement — computed once, locked thereafter. */
  initialLeaseLiability: number;
  /** Equals initialLeaseLiability at creation — no initial direct costs/lease incentives modeled. */
  initialRightOfUseAsset: number;
  /** Running total, maintained ONLY by leaseAmortizationService.runAmortization(). */
  accumulatedDepreciation: number;
  /** Running total, maintained ONLY by leaseAmortizationService.runAmortization() and set from initialLeaseLiability by leaseService.postCommencement(). */
  outstandingLeaseLiability: number;
  /** Set once postCommencement() posts the capitalization journal entry. */
  journalEntryId?: ID;
  terminationDate?: ISODateString;
  terminationJournalEntryId?: ID;
}

/**
 * Append-only lease amortization ledger row — one per lease per
 * amortization run, mirroring DepreciationEntry's shape exactly. The only
 * write path is leaseAmortizationService.runAmortization(); there is no
 * update()/delete().
 */
export interface LeaseAmortizationEntry extends BaseEntity {
  leaseId: ID;
  /** Date this amortization charge is calculated up to (the period-end chosen for the run). */
  periodEnd: ISODateString;
  interestAmount: number;
  /** payment - interest, capped so it never drives outstandingLeaseLiabilityAfter negative. */
  principalAmount: number;
  depreciationAmount: number;
  outstandingLeaseLiabilityAfter: number;
  accumulatedDepreciationAfter: number;
  /** The ONE combined journal entry for the whole run this row's amounts were part of. */
  journalEntryId: ID;
}
