import type { BaseEntity, ID, ISODateString } from './common';

/**
 * The kind of event that moved stock. Mirrors docs/INVENTORY_DOMAIN.md
 * § Perpetual Inventory Tracking triggers (GRN, Sales Invoice, Adjustment)
 * plus the transfer/opening-stock cases needed for multi-warehouse support.
 */
export type StockMovementType =
  | 'goods_received'
  | 'sale'
  | 'sales_return'
  | 'transfer_in'
  | 'transfer_out'
  | 'adjustment'
  | 'opening'
  // --- Inventory Accounting Module (Phase 2). Migration 0021.
  | 'purchase_return'
  | 'write_off'
  | 'stock_gain'
  | 'stock_take'
  | 'correction'
  // --- Phase 5C (Delivery Notes). Migration 0051.
  | 'delivery';

/** The kind of document a stock movement was generated by — the programmatic replacement for the free-text `reference`. */
export type StockMovementSourceType =
  | 'invoice'
  | 'bill'
  | 'credit_note'
  | 'purchase_order'
  | 'stock_adjustment'
  | 'stock_transfer'
  | 'stock_take'
  | 'opening_stock_batch'
  | 'supplier_return'
  | 'reversal'
  // --- Phase 5C (Delivery Notes).
  | 'delivery_note';

/**
 * A single immutable entry in the perpetual-inventory ledger. This is the
 * ONLY record of why a product's on-hand quantity at a warehouse changed —
 * per docs/DO_NOT_BREAK.md § Inventory & Stock, quantities are never
 * written directly; they are always derived by summing these entries
 * (see stockService.recordStockMovement / getQuantityOnHand).
 *
 * APPEND-ONLY: once created, a StockMovement is never mutated or deleted.
 * A correction is made by recording an offsetting movement (e.g. a second
 * 'adjustment' entry), never by editing history.
 */
export interface StockMovement extends BaseEntity {
  productId: ID;
  warehouseId: ID;
  type: StockMovementType;
  /** Signed change to quantity on hand. Positive = stock in, negative = stock out. */
  quantityDelta: number;
  /** Free-text reference to the source document (GRN number, invoice number, transfer batch id, etc.). */
  reference?: string;
  /** Required context for adjustments/opening stock (reason for write-off, damage, shrinkage, count variance, etc.). */
  notes?: string;

  // --- Inventory Accounting Module (Phase 2) additions. All optional;
  // NULL/undefined for the 284 movements created before migration 0022.
  // See docs/INVENTORY_ARCHITECTURE.md §11, §13.2.

  /** Weighted-average unit cost of the goods at the moment this movement was recorded. */
  unitCost?: number;
  /** `unitCost × |quantityDelta|`, at 2dp — what the movement was worth. */
  totalCost?: number;
  /** The business date of the movement (may differ from `createdAt`). */
  movementDate?: ISODateString;
  /** Structured link to the source document — replaces `reference` for traceability. */
  sourceDocumentType?: StockMovementSourceType;
  sourceDocumentId?: ID;
  sourceDocumentLineId?: ID;
  /** Who recorded the movement (user id or a `'system'` sentinel). */
  createdBy?: ID;
  /** For a `correction`/`reversal` movement: the movement it reverses. */
  reversalOfMovementId?: ID;
}
