import type { SupabaseClient } from '@supabase/supabase-js';
import type { NewStockTransferLine, StockTransfer, StockTransferHeader, StockTransferLine } from '@/types';
import type { IStockTransferRepository } from './IStockTransferRepository';
import { SupabaseNormalizedInventoryDocumentRepository as Base } from './SupabaseNormalizedInventoryDocumentRepository';
const s=(v:unknown)=>v as string,opt=(v:unknown)=>v==null?undefined:s(v),n=(v:unknown)=>Number(v),map=(r:Record<string,unknown>)=>Object.fromEntries(Object.entries(r).filter(([,v])=>v!==undefined));
export class SupabaseStockTransferRepository extends Base<StockTransfer,StockTransferLine,StockTransferHeader,NewStockTransferLine> implements IStockTransferRepository {constructor(client:SupabaseClient){super(client,{repositoryName:'SupabaseStockTransferRepository',headerTable:'stock_transfers',lineTable:'stock_transfer_lines',lineForeignKey:'stock_transfer_id',orderColumn:'transfer_number',
rowToHeader:r=>({id:s(r.id),createdAt:s(r.created_at),updatedAt:s(r.updated_at),transferNumber:s(r.transfer_number),fromWarehouseId:s(r.from_warehouse_id),toWarehouseId:s(r.to_warehouse_id),transferDate:s(r.transfer_date),expectedReceiptDate:opt(r.expected_receipt_date),receivedDate:opt(r.received_date),notes:opt(r.notes),totalCost:n(r.total_cost),status:s(r.status) as StockTransfer['status'],dispatchedJournalEntryId:opt(r.dispatched_journal_entry_id),receivedJournalEntryId:opt(r.received_journal_entry_id)}),
headerToRow:h=>map({transfer_number:h.transferNumber,from_warehouse_id:h.fromWarehouseId,to_warehouse_id:h.toWarehouseId,transfer_date:h.transferDate,expected_receipt_date:h.expectedReceiptDate,received_date:h.receivedDate,notes:h.notes,total_cost:h.totalCost,status:h.status,dispatched_journal_entry_id:h.dispatchedJournalEntryId,received_journal_entry_id:h.receivedJournalEntryId}),
rowToLine:r=>({id:s(r.id),transferId:s(r.stock_transfer_id),productId:s(r.product_id),quantity:n(r.quantity),unitCost:n(r.unit_cost),totalCost:n(r.total_cost)}),lineToRow:l=>map({product_id:l.productId,quantity:l.quantity,unit_cost:l.unitCost,total_cost:l.totalCost})});}}
